/*
 * Source: BuscausuBcaEstacion.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.estacionmantencion.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code ESTACION} of procedure {@code EstacionMantencion$BuscaUsu_bca}.
 *
 * <pre>
 * #ResultSet ESTACION ESTACIONES
 *   #Column  USU_CODIGO    NVARCHAR
 *   #Column  APELLIDO_PAT  NVARCHAR
 *   #Column  APELLIDO_MAT  NVARCHAR
 *   #Column  NOMBRES       NVARCHAR
 *   #Column  COMUNA        NVARCHAR
 *   #Column  CIUDAD        NVARCHAR
 *   #Column  PAIS          NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "buscausuBcaEstacion")
@XmlType(name = "BuscausuBcaEstacion")
public class BuscausuBcaEstacion implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String usuCodigo;
    private String apellidoPat;
    private String apellidoMat;
    private String nombres;
    private String comuna;
    private String ciudad;
    private String pais;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscausuBcaEstacion} instance.
     */
    public BuscausuBcaEstacion()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code usuCodigo}.
     *
     * @return the current value of the property.
     */
    public String getUsuCodigo()
    {
        return usuCodigo;
    }

    /**
     * Changes the value of property {@code usuCodigo}.
     *
     * @param value the new value of the property.
     */
    public void setUsuCodigo(final String value)
    {
        this.usuCodigo = value;
    }

    /**
     * Returns the value of property {@code apellidoPat}.
     *
     * @return the current value of the property.
     */
    public String getApellidoPat()
    {
        return apellidoPat;
    }

    /**
     * Changes the value of property {@code apellidoPat}.
     *
     * @param value the new value of the property.
     */
    public void setApellidoPat(final String value)
    {
        this.apellidoPat = value;
    }

    /**
     * Returns the value of property {@code apellidoMat}.
     *
     * @return the current value of the property.
     */
    public String getApellidoMat()
    {
        return apellidoMat;
    }

    /**
     * Changes the value of property {@code apellidoMat}.
     *
     * @param value the new value of the property.
     */
    public void setApellidoMat(final String value)
    {
        this.apellidoMat = value;
    }

    /**
     * Returns the value of property {@code nombres}.
     *
     * @return the current value of the property.
     */
    public String getNombres()
    {
        return nombres;
    }

    /**
     * Changes the value of property {@code nombres}.
     *
     * @param value the new value of the property.
     */
    public void setNombres(final String value)
    {
        this.nombres = value;
    }

    /**
     * Returns the value of property {@code comuna}.
     *
     * @return the current value of the property.
     */
    public String getComuna()
    {
        return comuna;
    }

    /**
     * Changes the value of property {@code comuna}.
     *
     * @param value the new value of the property.
     */
    public void setComuna(final String value)
    {
        this.comuna = value;
    }

    /**
     * Returns the value of property {@code ciudad}.
     *
     * @return the current value of the property.
     */
    public String getCiudad()
    {
        return ciudad;
    }

    /**
     * Changes the value of property {@code ciudad}.
     *
     * @param value the new value of the property.
     */
    public void setCiudad(final String value)
    {
        this.ciudad = value;
    }

    /**
     * Returns the value of property {@code pais}.
     *
     * @return the current value of the property.
     */
    public String getPais()
    {
        return pais;
    }

    /**
     * Changes the value of property {@code pais}.
     *
     * @param value the new value of the property.
     */
    public void setPais(final String value)
    {
        this.pais = value;
    }
}
