/*
 * Source: BuscaestBcaCaller.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.estacionmantencion.ws;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * Caller of procedure {@code EstacionMantencion$BuscaEst_bca}.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
public class BuscaestBcaCaller extends ProcedureCaller
{
    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaestBcaCaller} instance.
     */
    public BuscaestBcaCaller()
    {
    }

    //--------------------------------------------------------------------------
    //-- Execute Methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEst_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscaestBcaResult executeProc(final DataSource dataSource, String est)
        throws SQLException
    {
        try (final Connection conn = dataSource.getConnection()) {
            return executeProc(conn, est);
        }
    }

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEst_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscaestBcaResult executeProc(final Connection conn, String est)
        throws SQLException
    {
        final BuscaestBcaResult result = createProcResult();
        final String jdbcURL = getJdbcURL(conn);
        if (jdbcURL.startsWith("jdbc:oracle:")) {
            try (final CallableStatement call = prepareCall(conn, "{call EstacionMantencion$BuscaEst_bca(?,?,?)}")) {
                call.setString(1, est);
                call.registerOutParameter(2, Types.NVARCHAR);
                call.registerOutParameter(3, ORACLE_CURSOR);
                call.execute();
                result.setErrorMessage(call.getString(2));
                result.setEstaciones(readEstaciones((ResultSet) call.getObject(3)));
            }
        } else if (jdbcURL.startsWith("jdbc:postgresql:")) {
            try (final CallableStatement call = prepareCall(conn, "{call EstacionMantencion$BuscaEst_bca(?,?,?)}")) {
                call.setString(1, est);
                call.registerOutParameter(2, Types.NVARCHAR);
                call.registerOutParameter(3, Types.OTHER);
                call.execute();
                result.setErrorMessage(call.getString(2));
                result.setEstaciones(readEstaciones((ResultSet) call.getObject(3)));
            }
        } else {
            try (final CallableStatement call = prepareCall(conn, "{call EstacionMantencion$BuscaEst_bca(?,?)}")) {
                call.setString(1, est);
                call.registerOutParameter(2, Types.NVARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset) {
                        updateCount = call.getUpdateCount();
                    } else if (result.getEstaciones() == null) {
                        result.setEstaciones(readEstaciones(call.getResultSet()));
                    } else {
                        unexpectedResultSet(call.getResultSet());
                    }
                    haveRset = call.getMoreResults();
                }
                result.setErrorMessage(call.getString(2));
            }
        }
        return result;
    }

    /**
     * Creates and returns a new instance of {@code BuscaestBcaResult}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscaestBcaResult}.
     *
     * @return a new {@code BuscaestBcaResult} instance.
     */
    protected BuscaestBcaResult createProcResult()
    {
        return new BuscaestBcaResult();
    }

    //--------------------------------------------------------------------------
    //-- BuscaestBcaEstacion ResultSet Methods ---------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts a result set to an array of {@code BuscaestBcaEstacion}.
     *
     * @param  resultSet the result set to convert (can be null).
     * @return an array of {@code BuscaestBcaEstacion} or null.
     * @throws SQLException if an SQL error occurs.
     */
    protected List<BuscaestBcaEstacion> readEstaciones(final ResultSet resultSet)
        throws SQLException
    {
        if (resultSet == null)
            return null;
        try {
            // Obtain ordinal (index) numbers of result columns
            final int cEstacion = resultSet.findColumn("ESTACION");
            final int cCodEmp = resultSet.findColumn("COD_EMP");
            final int cTipoestacion = resultSet.findColumn("TIPOESTACION");
            final int cDescripcion = resultSet.findColumn("DESCRIPCION");
            final int cSucursalRandom = resultSet.findColumn("SUCURSAL_RANDOM");
            final int cEstacionRandom = resultSet.findColumn("ESTACION_RANDOM");

            // Convert result rows to an array of "BuscaestBcaEstacion"
            final List<BuscaestBcaEstacion> list = new ArrayList<>();
            while (resultSet.next()) {
                final BuscaestBcaEstacion item = createEstacion();
                item.setEstacion(resultSet.getString(cEstacion));
                item.setCodEmp(resultSet.getString(cCodEmp));
                item.setTipoestacion(resultSet.getString(cTipoestacion));
                item.setDescripcion(resultSet.getString(cDescripcion));
                item.setSucursalRandom(resultSet.getString(cSucursalRandom));
                item.setEstacionRandom(resultSet.getString(cEstacionRandom));
                if (filterEstacion(item)) list.add(item);
            }
            return list;
        } finally {
            resultSet.close();
        }
    }

    /**
     * Creates and returns a new instance of {@code BuscaestBcaEstacion}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscaestBcaEstacion}.
     *
     * @return a new {@code BuscaestBcaEstacion} instance.
     */
    protected BuscaestBcaEstacion createEstacion()
    {
        return new BuscaestBcaEstacion();
    }

    /**
     * Returns {@code true} if supplied item should be added to result set.
     * <p>
     * Can be overridden to select which items are added to the result set.
     *
     * @param  item the {@code BuscaestBcaEstacion} to be checked.
     * @return {@code true} if {@code item} should be added to result set.
     * @throws NullPointerException if {@code item} is {@code null}.
     */
    protected boolean filterEstacion(final BuscaestBcaEstacion item)
    {
        return true;
    }

    //--------------------------------------------------------------------------
    //-- Static Methods --------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEst_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscaestBcaResult execute(final DataSource dataSource, String est)
        throws SQLException
    {
        return new BuscaestBcaCaller().executeProc(dataSource, est);
    }

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEst_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscaestBcaResult execute(final Connection conn, String est)
        throws SQLException
    {
        return new BuscaestBcaCaller().executeProc(conn, est);
    }
}
