/*
 * Source: BuscaestBcaResult.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.estacionmantencion.ws;

import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Results of procedure {@code EstacionMantencion$BuscaEst_bca}.
 *
 * <pre>
 * Error_Message  nvarchar   Output
 * ESTACION       ResultSet  Output
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "buscaestBcaResult")
@XmlType(name = "BuscaestBcaResult")
public class BuscaestBcaResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private String errorMessage;
    private List<BuscaestBcaEstacion> estaciones;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaestBcaResult} instance.
     */
    public BuscaestBcaResult()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code errorMessage}.
     *
     * @return the current value of the property.
     */
    public String getErrorMessage()
    {
        return errorMessage;
    }

    /**
     * Changes the value of property {@code errorMessage}.
     *
     * @param value the new value of the property.
     */
    public void setErrorMessage(final String value)
    {
        this.errorMessage = value;
    }

    /**
     * Returns the value of property {@code estaciones}.
     *
     * @return the current value of the property.
     */
    public List<BuscaestBcaEstacion> getEstaciones()
    {
        return estaciones;
    }

    /**
     * Changes the value of property {@code estaciones}.
     *
     * @param value the new value of the property.
     */
    public void setEstaciones(final List<BuscaestBcaEstacion> value)
    {
        this.estaciones = value;
    }
}
