/*
 * Source: EstacionMantencionWeb.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.estacionmantencion.ws;

import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import javax.transaction.UserTransaction;

/**
 * The {@code EstacionMantencion} Web Service.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@WebService(targetNamespace = EstacionMantencionWeb.TNS)
public class EstacionMantencionWeb
{
    /** The Target Namespace of the Web Service. */
    public static final String TNS = "http://ws.estacionmantencion.imperial.cl/estacionmantencion";

    /** The Logger of the Web Service. */
    private static final Logger logger =
        Logger.getLogger(EstacionMantencionWeb.class.getName());

    /** The User Transaction of the Web Service. */
    @Resource(name = "userTransaction")
    private UserTransaction userTransaction;

    /** The Data Source of the Web Service. */
    @Resource(name = "EstacionMantencionDataSource")
    private DataSource dataSource;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code EstacionMantencionWeb} instance.
     */
    public EstacionMantencionWeb()
    {
    }

    //--------------------------------------------------------------------------
    //-- WebService Methods ----------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEmp_bca}.
     *
     * @return the output parameters and result sets of the procedure.
     * @throws EstacionMantencionWebException if an error occurs.
     */
    @WebMethod(operationName = "buscaempBca")
    @WebResult(name = "buscaempBcaResult", targetNamespace = TNS)
    public BuscaempBcaResult buscaempBca()
        throws EstacionMantencionWebException
    {
        final BuscaempBcaResult result;
        try {
            getUserTransaction().begin();
            try {
                result = BuscaempBcaCaller.execute(getDataSource());
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "buscaempBca");
            throw new EstacionMantencionWebException(thrown, "buscaempBca");
        }
        return result;
    }

    /**
     * Executes procedure {@code EstacionMantencion$BuscaEst_bca}.
     *
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EstacionMantencionWebException if an error occurs.
     */
    @WebMethod(operationName = "buscaestBca")
    @WebResult(name = "buscaestBcaResult", targetNamespace = TNS)
    public BuscaestBcaResult buscaestBca(
        @WebParam(name = "est", targetNamespace = TNS) final String est)
        throws EstacionMantencionWebException
    {
        final BuscaestBcaResult result;
        try {
            getUserTransaction().begin();
            try {
                result = BuscaestBcaCaller.execute(getDataSource(), est);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "buscaestBca");
            throw new EstacionMantencionWebException(thrown, "buscaestBca");
        }
        return result;
    }

    /**
     * Executes procedure {@code EstacionMantencion$BuscaUsu_bca}.
     *
     * @param  usuCodigo {@code USU_CODIGO char(40)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EstacionMantencionWebException if an error occurs.
     */
    @WebMethod(operationName = "buscausuBca")
    @WebResult(name = "buscausuBcaResult", targetNamespace = TNS)
    public BuscausuBcaResult buscausuBca(
        @WebParam(name = "usuCodigo", targetNamespace = TNS) final String usuCodigo)
        throws EstacionMantencionWebException
    {
        final BuscausuBcaResult result;
        try {
            getUserTransaction().begin();
            try {
                result = BuscausuBcaCaller.execute(getDataSource(), usuCodigo);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "buscausuBca");
            throw new EstacionMantencionWebException(thrown, "buscausuBca");
        }
        return result;
    }

    /**
     * Executes procedure {@code EstacionMantencion$EliminaEst_eli}.
     *
     * @param  est {@code Est char(50)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EstacionMantencionWebException if an error occurs.
     */
    @WebMethod(operationName = "eliminaestEli")
    @WebResult(name = "eliminaestEliResult", targetNamespace = TNS)
    public EliminaestEliResult eliminaestEli(
        @WebParam(name = "est", targetNamespace = TNS) final String est)
        throws EstacionMantencionWebException
    {
        final EliminaestEliResult result;
        try {
            getUserTransaction().begin();
            try {
                result = EliminaestEliCaller.execute(getDataSource(), est);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "eliminaestEli");
            throw new EstacionMantencionWebException(thrown, "eliminaestEli");
        }
        return result;
    }

    /**
     * Executes procedure {@code EstacionMantencion$IngresaEst_ins}.
     *
     * @param  est {@code Est char(50)}.
     * @param  emp {@code Emp char(8)}.
     * @param  tipoest {@code TipoEst char(20)}.
     * @param  desc {@code Desc varchar(150)}.
     * @param  sucran {@code SucRan char(3)}.
     * @param  estran {@code EstRan char(2)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EstacionMantencionWebException if an error occurs.
     */
    @WebMethod(operationName = "ingresaestIns")
    @WebResult(name = "ingresaestInsResult", targetNamespace = TNS)
    public IngresaestInsResult ingresaestIns(
        @WebParam(name = "est", targetNamespace = TNS) final String est,
        @WebParam(name = "emp", targetNamespace = TNS) final String emp,
        @WebParam(name = "tipoest", targetNamespace = TNS) final String tipoest,
        @WebParam(name = "desc", targetNamespace = TNS) final String desc,
        @WebParam(name = "sucran", targetNamespace = TNS) final String sucran,
        @WebParam(name = "estran", targetNamespace = TNS) final String estran)
        throws EstacionMantencionWebException
    {
        final IngresaestInsResult result;
        try {
            getUserTransaction().begin();
            try {
                result = IngresaestInsCaller.execute(getDataSource(), est, emp, tipoest, desc, sucran, estran);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "ingresaestIns");
            throw new EstacionMantencionWebException(thrown, "ingresaestIns");
        }
        return result;
    }

    //--------------------------------------------------------------------------
    //-- JNDI Methods ----------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the user transaction of the WebService.
     *
     * @return the user transaction of the WebService.
     * @throws NamingException if a JNDI error occurs.
     */
    private UserTransaction getUserTransaction()
        throws NamingException
    {
        if (userTransaction == null) {
            final InitialContext context = new InitialContext();
            try {
                userTransaction = (UserTransaction) context.lookup("java:comp/UserTransaction");
            } finally {
                context.close();
            }
        }
        return userTransaction;
    }

    /**
     * Returns the data source of the WebService.
     *
     * @return the data source of the WebService.
     * @throws NamingException if a JNDI error occurs.
     */
    private DataSource getDataSource()
        throws NamingException
    {
        if (dataSource == null) {
            final InitialContext context = new InitialContext();
            try {
                dataSource = (DataSource) context.lookup("java:comp/env/EstacionMantencionDataSource");
            } finally {
                context.close();
            }
        }
        return dataSource;
    }

    //--------------------------------------------------------------------------
    //-- Error Methods ---------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Logs a method error with associated throwable information.
     *
     * @param thrown the throwable associated with the error.
     * @param methodName the name of method that threw the error.
     */
    private void logError(final Throwable thrown, final String methodName)
    {
        if (thrown instanceof SQLException) {
            logSqlError((SQLException) thrown, methodName);
        } else {
            final String fullName = getClass().getName() + '#' + methodName;
            logger.log(Level.SEVERE, "Error executing " + fullName, thrown);
        }
    }

    /**
     * Logs a method error with associated SQLException information.
     *
     * @param  sqlex the SQLException associated with the error.
     * @param  methodName the name of method that threw the error.
     * @throws NullPointerException if {@code sqlex} is {@code null}.
     */
    private void logSqlError(final SQLException sqlex, final String methodName)
    {
        // Compute full method name and obtain SQL properties
        final String fullName = getClass().getName() + '#' + methodName;
        final String sqlState = sqlex.getSQLState();
        final int sqlErrorCode = sqlex.getErrorCode();

        // Obtain all error messages of SQLException
        final StringBuilder sb = new StringBuilder(200);
        final Iterator<Throwable> iter = sqlex.iterator();
        while (iter.hasNext()) {
            final Throwable cause = iter.next();
            if (sb.length() > 0) sb.append(": ");
            final String msg = cause.getMessage();
            sb.append(msg != null ? msg : cause.toString());
        }
        final String sqlMessages = sb.toString();

        // Log error including full method name and SQL properties
        final String sqlProps = ": (" + sqlState + ',' + sqlErrorCode + ") ";
        logger.severe("Error executing " + fullName + sqlProps + sqlMessages);
    }
}
