/*
 * Source: IngresaestInsRegistro.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.estacionmantencion.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code REGISTRO} of procedure {@code EstacionMantencion$IngresaEst_ins}.
 *
 * <pre>
 * #ResultSet REGISTRO REGISTROS
 *   #Column  INS  NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "ingresaestInsRegistro")
@XmlType(name = "IngresaestInsRegistro")
public class IngresaestInsRegistro implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String ins;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code IngresaestInsRegistro} instance.
     */
    public IngresaestInsRegistro()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code ins}.
     *
     * @return the current value of the property.
     */
    public String getIns()
    {
        return ins;
    }

    /**
     * Changes the value of property {@code ins}.
     *
     * @param value the new value of the property.
     */
    public void setIns(final String value)
    {
        this.ins = value;
    }
}
