
package cl.imperial.tipodocumento.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TipoDocumentoWebService", targetNamespace = "http://ws.tipodocumento.imperial.cl/tipodocumento", wsdlLocation = "TipoDocumentoWebService.wsdl")
public class TipoDocumentoWebService
    extends Service
{

    private final static URL TIPODOCUMENTOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIPODOCUMENTOWEBSERVICE_EXCEPTION;
    private final static QName TIPODOCUMENTOWEBSERVICE_QNAME = new QName("http://ws.tipodocumento.imperial.cl/tipodocumento", "TipoDocumentoWebService");

    static {
        TIPODOCUMENTOWEBSERVICE_WSDL_LOCATION = cl.imperial.tipodocumento.ws.TipoDocumentoWebService.class.getResource("TipoDocumentoWebService.wsdl");
        WebServiceException e = null;
        if (TIPODOCUMENTOWEBSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'TipoDocumentoWebService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TIPODOCUMENTOWEBSERVICE_EXCEPTION = e;
    }

    public TipoDocumentoWebService() {
        super(__getWsdlLocation(), TIPODOCUMENTOWEBSERVICE_QNAME);
    }

    public TipoDocumentoWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIPODOCUMENTOWEBSERVICE_QNAME, features);
    }

    public TipoDocumentoWebService(URL wsdlLocation) {
        super(wsdlLocation, TIPODOCUMENTOWEBSERVICE_QNAME);
    }

    public TipoDocumentoWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIPODOCUMENTOWEBSERVICE_QNAME, features);
    }

    public TipoDocumentoWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TipoDocumentoWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TipoDocumentoWeb
     */
    @WebEndpoint(name = "TipoDocumentoWebPort")
    public TipoDocumentoWeb getTipoDocumentoWebPort() {
        return super.getPort(new QName("http://ws.tipodocumento.imperial.cl/tipodocumento", "TipoDocumentoWebPort"), TipoDocumentoWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TipoDocumentoWeb
     */
    @WebEndpoint(name = "TipoDocumentoWebPort")
    public TipoDocumentoWeb getTipoDocumentoWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.tipodocumento.imperial.cl/tipodocumento", "TipoDocumentoWebPort"), TipoDocumentoWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIPODOCUMENTOWEBSERVICE_EXCEPTION!= null) {
            throw TIPODOCUMENTOWEBSERVICE_EXCEPTION;
        }
        return TIPODOCUMENTOWEBSERVICE_WSDL_LOCATION;
    }

}
