
package cl.imperial.escanerproducto.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EscanerProductoWeb", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EscanerProductoWeb {


    /**
     * 
     * @param vcodigo
     * @param vcodSucursal
     * @param vtipoDoc
     * @param vcodLista
     * @param vcodEntidad
     * @param vtipo
     * @param vcodEmp
     * @return
     *     returns cl.imperial.escanerproducto.ws.TraelecturascanResult
     * @throws EscanerProductoWebException
     */
    @WebMethod
    @WebResult(name = "traelecturascanResult", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
    @RequestWrapper(localName = "traelecturascan", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto", className = "cl.imperial.escanerproducto.ws.Traelecturascan")
    @ResponseWrapper(localName = "traelecturascanResponse", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto", className = "cl.imperial.escanerproducto.ws.TraelecturascanResponse")
    @Action(input = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/traelecturascanRequest", output = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/traelecturascanResponse", fault = {
        @FaultAction(className = EscanerProductoWebException.class, value = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/traelecturascan/Fault/EscanerProductoWebException")
    })
    public TraelecturascanResult traelecturascan(
        @WebParam(name = "vcodigo", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodigo,
        @WebParam(name = "vtipo", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vtipo,
        @WebParam(name = "vcodLista", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodLista,
        @WebParam(name = "vcodEmp", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodEmp,
        @WebParam(name = "vcodEntidad", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodEntidad,
        @WebParam(name = "vcodSucursal", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodSucursal,
        @WebParam(name = "vtipoDoc", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vtipoDoc)
        throws EscanerProductoWebException
    ;

    /**
     * 
     * @param vestacion
     * @param vcodSucursal
     * @param vxmlproductos
     * @param vtipodoc
     * @param vusuario
     * @param vcodLista
     * @param vcodEntidad
     * @param vcodEmp
     * @return
     *     returns cl.imperial.escanerproducto.ws.GrabavaletranstorioResult
     * @throws EscanerProductoWebException
     */
    @WebMethod
    @WebResult(name = "grabavaletranstorioResult", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
    @RequestWrapper(localName = "grabavaletranstorio", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto", className = "cl.imperial.escanerproducto.ws.Grabavaletranstorio")
    @ResponseWrapper(localName = "grabavaletranstorioResponse", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto", className = "cl.imperial.escanerproducto.ws.GrabavaletranstorioResponse")
    @Action(input = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/grabavaletranstorioRequest", output = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/grabavaletranstorioResponse", fault = {
        @FaultAction(className = EscanerProductoWebException.class, value = "http://ws.escanerproducto.imperial.cl/escanerproducto/EscanerProductoWeb/grabavaletranstorio/Fault/EscanerProductoWebException")
    })
    public GrabavaletranstorioResult grabavaletranstorio(
        @WebParam(name = "vxmlproductos", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vxmlproductos,
        @WebParam(name = "vcodEmp", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodEmp,
        @WebParam(name = "vusuario", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vusuario,
        @WebParam(name = "vtipodoc", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vtipodoc,
        @WebParam(name = "vcodEntidad", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodEntidad,
        @WebParam(name = "vcodSucursal", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodSucursal,
        @WebParam(name = "vcodLista", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vcodLista,
        @WebParam(name = "vestacion", targetNamespace = "http://ws.escanerproducto.imperial.cl/escanerproducto")
        String vestacion)
        throws EscanerProductoWebException
    ;

}
