/*
 * Source: RegistraPagoResult.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Nicolás Uribe Valenzuela (IMPERIAL S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.cajaunificada.ws;

import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Results of procedure {@code CajaUnificada$Registra_Pago}.
 *
 * <pre>
 * DTE_TIPO_DOCUMENTO         nvarchar   Output
 * DTE_FECHA_HORA_EMISION     datetime   Output
 * DTE_FOLIO                  nvarchar   Output
 * DTE_OBSERVACIONES          nvarchar   Output
 * EMISOR_RUT                 nvarchar   Output
 * EMISOR_DV                  nvarchar   Output
 * EMISOR_RAZON_SOCIAL        nvarchar   Output
 * EMISOR_GIRO                nvarchar   Output
 * EMISOR_DIRECCION_MATRIZ    nvarchar   Output
 * EMISOR_DIRECCION_SUCURSAL  nvarchar   Output
 * EMISOR_VENDEDOR            nvarchar   Output
 * CLIENTE_RAZON_SOCIAL       nvarchar   Output
 * CLIENTE_RUT                nvarchar   Output
 * CLIENTE_DV                 nvarchar   Output
 * CLIENTE_DIRECCION          nvarchar   Output
 * CLIENTE_COMUNA             nvarchar   Output
 * CLIENTE_CIUDAD             nvarchar   Output
 * CLIENTE_ORDEN_COMPRA       nvarchar   Output
 * CLIENTE_CONDICIONES        nvarchar   Output
 * TOTAL_NETO                 int        Output
 * IVA                        int        Output
 * TOTAL                      int        Output
 * DETALLE                    ResultSet  Output
 * </pre>
 *
 * @author Nicolás Uribe Valenzuela (IMPERIAL S.A.)
 */
@XmlRootElement(name = "registraPagoResult")
@XmlType(name = "RegistraPagoResult")
public class RegistraPagoResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private String dteTipoDocumento;
    private Date dteFechaHoraEmision;
    private String dteFolio;
    private String dteObservaciones;
    private String emisorRut;
    private String emisorDv;
    private String emisorRazonSocial;
    private String emisorGiro;
    private String emisorDireccionMatriz;
    private String emisorDireccionSucursal;
    private String emisorVendedor;
    private String clienteRazonSocial;
    private String clienteRut;
    private String clienteDv;
    private String clienteDireccion;
    private String clienteComuna;
    private String clienteCiudad;
    private String clienteOrdenCompra;
    private String clienteCondiciones;
    private int totalNeto;
    private int iva;
    private int total;
    private List<RegistraPagoDetalle> detalles;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code RegistraPagoResult} instance.
     */
    public RegistraPagoResult()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code dteTipoDocumento}.
     *
     * @return the current value of the property.
     */
    public String getDteTipoDocumento()
    {
        return dteTipoDocumento;
    }

    /**
     * Changes the value of property {@code dteTipoDocumento}.
     *
     * @param value the new value of the property.
     */
    public void setDteTipoDocumento(final String value)
    {
        this.dteTipoDocumento = value;
    }

    /**
     * Returns the value of property {@code dteFechaHoraEmision}.
     *
     * @return the current value of the property.
     */
    public Date getDteFechaHoraEmision()
    {
        return dteFechaHoraEmision;
    }

    /**
     * Changes the value of property {@code dteFechaHoraEmision}.
     *
     * @param value the new value of the property.
     */
    public void setDteFechaHoraEmision(final Date value)
    {
        this.dteFechaHoraEmision = value;
    }

    /**
     * Returns the value of property {@code dteFolio}.
     *
     * @return the current value of the property.
     */
    public String getDteFolio()
    {
        return dteFolio;
    }

    /**
     * Changes the value of property {@code dteFolio}.
     *
     * @param value the new value of the property.
     */
    public void setDteFolio(final String value)
    {
        this.dteFolio = value;
    }

    /**
     * Returns the value of property {@code dteObservaciones}.
     *
     * @return the current value of the property.
     */
    public String getDteObservaciones()
    {
        return dteObservaciones;
    }

    /**
     * Changes the value of property {@code dteObservaciones}.
     *
     * @param value the new value of the property.
     */
    public void setDteObservaciones(final String value)
    {
        this.dteObservaciones = value;
    }

    /**
     * Returns the value of property {@code emisorRut}.
     *
     * @return the current value of the property.
     */
    public String getEmisorRut()
    {
        return emisorRut;
    }

    /**
     * Changes the value of property {@code emisorRut}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorRut(final String value)
    {
        this.emisorRut = value;
    }

    /**
     * Returns the value of property {@code emisorDv}.
     *
     * @return the current value of the property.
     */
    public String getEmisorDv()
    {
        return emisorDv;
    }

    /**
     * Changes the value of property {@code emisorDv}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorDv(final String value)
    {
        this.emisorDv = value;
    }

    /**
     * Returns the value of property {@code emisorRazonSocial}.
     *
     * @return the current value of the property.
     */
    public String getEmisorRazonSocial()
    {
        return emisorRazonSocial;
    }

    /**
     * Changes the value of property {@code emisorRazonSocial}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorRazonSocial(final String value)
    {
        this.emisorRazonSocial = value;
    }

    /**
     * Returns the value of property {@code emisorGiro}.
     *
     * @return the current value of the property.
     */
    public String getEmisorGiro()
    {
        return emisorGiro;
    }

    /**
     * Changes the value of property {@code emisorGiro}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorGiro(final String value)
    {
        this.emisorGiro = value;
    }

    /**
     * Returns the value of property {@code emisorDireccionMatriz}.
     *
     * @return the current value of the property.
     */
    public String getEmisorDireccionMatriz()
    {
        return emisorDireccionMatriz;
    }

    /**
     * Changes the value of property {@code emisorDireccionMatriz}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorDireccionMatriz(final String value)
    {
        this.emisorDireccionMatriz = value;
    }

    /**
     * Returns the value of property {@code emisorDireccionSucursal}.
     *
     * @return the current value of the property.
     */
    public String getEmisorDireccionSucursal()
    {
        return emisorDireccionSucursal;
    }

    /**
     * Changes the value of property {@code emisorDireccionSucursal}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorDireccionSucursal(final String value)
    {
        this.emisorDireccionSucursal = value;
    }

    /**
     * Returns the value of property {@code emisorVendedor}.
     *
     * @return the current value of the property.
     */
    public String getEmisorVendedor()
    {
        return emisorVendedor;
    }

    /**
     * Changes the value of property {@code emisorVendedor}.
     *
     * @param value the new value of the property.
     */
    public void setEmisorVendedor(final String value)
    {
        this.emisorVendedor = value;
    }

    /**
     * Returns the value of property {@code clienteRazonSocial}.
     *
     * @return the current value of the property.
     */
    public String getClienteRazonSocial()
    {
        return clienteRazonSocial;
    }

    /**
     * Changes the value of property {@code clienteRazonSocial}.
     *
     * @param value the new value of the property.
     */
    public void setClienteRazonSocial(final String value)
    {
        this.clienteRazonSocial = value;
    }

    /**
     * Returns the value of property {@code clienteRut}.
     *
     * @return the current value of the property.
     */
    public String getClienteRut()
    {
        return clienteRut;
    }

    /**
     * Changes the value of property {@code clienteRut}.
     *
     * @param value the new value of the property.
     */
    public void setClienteRut(final String value)
    {
        this.clienteRut = value;
    }

    /**
     * Returns the value of property {@code clienteDv}.
     *
     * @return the current value of the property.
     */
    public String getClienteDv()
    {
        return clienteDv;
    }

    /**
     * Changes the value of property {@code clienteDv}.
     *
     * @param value the new value of the property.
     */
    public void setClienteDv(final String value)
    {
        this.clienteDv = value;
    }

    /**
     * Returns the value of property {@code clienteDireccion}.
     *
     * @return the current value of the property.
     */
    public String getClienteDireccion()
    {
        return clienteDireccion;
    }

    /**
     * Changes the value of property {@code clienteDireccion}.
     *
     * @param value the new value of the property.
     */
    public void setClienteDireccion(final String value)
    {
        this.clienteDireccion = value;
    }

    /**
     * Returns the value of property {@code clienteComuna}.
     *
     * @return the current value of the property.
     */
    public String getClienteComuna()
    {
        return clienteComuna;
    }

    /**
     * Changes the value of property {@code clienteComuna}.
     *
     * @param value the new value of the property.
     */
    public void setClienteComuna(final String value)
    {
        this.clienteComuna = value;
    }

    /**
     * Returns the value of property {@code clienteCiudad}.
     *
     * @return the current value of the property.
     */
    public String getClienteCiudad()
    {
        return clienteCiudad;
    }

    /**
     * Changes the value of property {@code clienteCiudad}.
     *
     * @param value the new value of the property.
     */
    public void setClienteCiudad(final String value)
    {
        this.clienteCiudad = value;
    }

    /**
     * Returns the value of property {@code clienteOrdenCompra}.
     *
     * @return the current value of the property.
     */
    public String getClienteOrdenCompra()
    {
        return clienteOrdenCompra;
    }

    /**
     * Changes the value of property {@code clienteOrdenCompra}.
     *
     * @param value the new value of the property.
     */
    public void setClienteOrdenCompra(final String value)
    {
        this.clienteOrdenCompra = value;
    }

    /**
     * Returns the value of property {@code clienteCondiciones}.
     *
     * @return the current value of the property.
     */
    public String getClienteCondiciones()
    {
        return clienteCondiciones;
    }

    /**
     * Changes the value of property {@code clienteCondiciones}.
     *
     * @param value the new value of the property.
     */
    public void setClienteCondiciones(final String value)
    {
        this.clienteCondiciones = value;
    }

    /**
     * Returns the value of property {@code totalNeto}.
     *
     * @return the current value of the property.
     */
    public int getTotalNeto()
    {
        return totalNeto;
    }

    /**
     * Changes the value of property {@code totalNeto}.
     *
     * @param value the new value of the property.
     */
    public void setTotalNeto(final int value)
    {
        this.totalNeto = value;
    }

    /**
     * Returns the value of property {@code iva}.
     *
     * @return the current value of the property.
     */
    public int getIva()
    {
        return iva;
    }

    /**
     * Changes the value of property {@code iva}.
     *
     * @param value the new value of the property.
     */
    public void setIva(final int value)
    {
        this.iva = value;
    }

    /**
     * Returns the value of property {@code total}.
     *
     * @return the current value of the property.
     */
    public int getTotal()
    {
        return total;
    }

    /**
     * Changes the value of property {@code total}.
     *
     * @param value the new value of the property.
     */
    public void setTotal(final int value)
    {
        this.total = value;
    }

    /**
     * Returns the value of property {@code detalles}.
     *
     * @return the current value of the property.
     */
    public List<RegistraPagoDetalle> getDetalles()
    {
        return detalles;
    }

    /**
     * Changes the value of property {@code detalles}.
     *
     * @param value the new value of the property.
     */
    public void setDetalles(final List<RegistraPagoDetalle> value)
    {
        this.detalles = value;
    }
}
