/*
 * Source: ValeGetResult.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Nicolás Uribe Valenzuela (IMPERIAL S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.cajaunificada.ws;

import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Results of procedure {@code CajaUnificada$Vale_Get}.
 *
 * <pre>
 * NOMBRE_CLIENTE  nvarchar  Output
 * FECHA_EMISION   datetime  Output
 * DESCUENTO       int       Output
 * MONTO           int       Output
 * TIPO_DOCUMENTO  nvarchar  Output
 * </pre>
 *
 * @author Nicolás Uribe Valenzuela (IMPERIAL S.A.)
 */
@XmlRootElement(name = "valeGetResult")
@XmlType(name = "ValeGetResult")
public class ValeGetResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private String nombreCliente;
    private Date fechaEmision;
    private int descuento;
    private int monto;
    private String tipoDocumento;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code ValeGetResult} instance.
     */
    public ValeGetResult()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code nombreCliente}.
     *
     * @return the current value of the property.
     */
    public String getNombreCliente()
    {
        return nombreCliente;
    }

    /**
     * Changes the value of property {@code nombreCliente}.
     *
     * @param value the new value of the property.
     */
    public void setNombreCliente(final String value)
    {
        this.nombreCliente = value;
    }

    /**
     * Returns the value of property {@code fechaEmision}.
     *
     * @return the current value of the property.
     */
    public Date getFechaEmision()
    {
        return fechaEmision;
    }

    /**
     * Changes the value of property {@code fechaEmision}.
     *
     * @param value the new value of the property.
     */
    public void setFechaEmision(final Date value)
    {
        this.fechaEmision = value;
    }

    /**
     * Returns the value of property {@code descuento}.
     *
     * @return the current value of the property.
     */
    public int getDescuento()
    {
        return descuento;
    }

    /**
     * Changes the value of property {@code descuento}.
     *
     * @param value the new value of the property.
     */
    public void setDescuento(final int value)
    {
        this.descuento = value;
    }

    /**
     * Returns the value of property {@code monto}.
     *
     * @return the current value of the property.
     */
    public int getMonto()
    {
        return monto;
    }

    /**
     * Changes the value of property {@code monto}.
     *
     * @param value the new value of the property.
     */
    public void setMonto(final int value)
    {
        this.monto = value;
    }

    /**
     * Returns the value of property {@code tipoDocumento}.
     *
     * @return the current value of the property.
     */
    public String getTipoDocumento()
    {
        return tipoDocumento;
    }

    /**
     * Changes the value of property {@code tipoDocumento}.
     *
     * @param value the new value of the property.
     */
    public void setTipoDocumento(final String value)
    {
        this.tipoDocumento = value;
    }
}
