<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.autorizadorventa.imperial.cl/autorizadorventa" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws.autorizadorventa.imperial.cl/autorizadorventa" name="AutorizadorVentaWebService">
<types>
<xsd:schema>
<xsd:import namespace="http://ws.autorizadorventa.imperial.cl/autorizadorventa" schemaLocation="AutorizadorVentaWebService.xsd"/>
</xsd:schema>
</types>
<message name="buscaclienterutBca">
<part name="parameters" element="tns:buscaclienterutBca"/>
</message>
<message name="buscaclienterutBcaResponse">
<part name="parameters" element="tns:buscaclienterutBcaResponse"/>
</message>
<message name="AutorizadorVentaWebException">
<part name="fault" element="tns:faultinfo"/>
</message>
<portType name="AutorizadorVentaWeb">
<operation name="buscaclienterutBca">
<input wsam:Action="http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBcaRequest" message="tns:buscaclienterutBca"/>
<output wsam:Action="http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBcaResponse" message="tns:buscaclienterutBcaResponse"/>
<fault message="tns:AutorizadorVentaWebException" name="AutorizadorVentaWebException" wsam:Action="http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBca/Fault/AutorizadorVentaWebException"/>
</operation>
</portType>
<binding name="AutorizadorVentaWebPortBinding" type="tns:AutorizadorVentaWeb">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="buscaclienterutBca">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault name="AutorizadorVentaWebException">
<soap:fault name="AutorizadorVentaWebException" use="literal"/>
</fault>
</operation>
</binding>
<service name="AutorizadorVentaWebService">
<port name="AutorizadorVentaWebPort" binding="tns:AutorizadorVentaWebPortBinding">
<soap:address location="http://localhost:8080/autorizadorventa/AutorizadorVentaWebService"/>
</port>
</service>
</definitions>