
package cl.imperial.autorizadorventa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutorizadorVentaWeb", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutorizadorVentaWeb {


    /**
     * 
     * @param codSucursal
     * @param rutCliente
     * @param codEntidad
     * @return
     *     returns cl.imperial.autorizadorventa.ws.BuscaclienterutBcaResult
     * @throws AutorizadorVentaWebException
     */
    @WebMethod
    @WebResult(name = "buscaclienterutBcaResult", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa")
    @RequestWrapper(localName = "buscaclienterutBca", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa", className = "cl.imperial.autorizadorventa.ws.BuscaclienterutBca")
    @ResponseWrapper(localName = "buscaclienterutBcaResponse", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa", className = "cl.imperial.autorizadorventa.ws.BuscaclienterutBcaResponse")
    @Action(input = "http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBcaRequest", output = "http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBcaResponse", fault = {
        @FaultAction(className = AutorizadorVentaWebException.class, value = "http://ws.autorizadorventa.imperial.cl/autorizadorventa/AutorizadorVentaWeb/buscaclienterutBca/Fault/AutorizadorVentaWebException")
    })
    public BuscaclienterutBcaResult buscaclienterutBca(
        @WebParam(name = "rutCliente", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa")
        String rutCliente,
        @WebParam(name = "codEntidad", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa")
        String codEntidad,
        @WebParam(name = "codSucursal", targetNamespace = "http://ws.autorizadorventa.imperial.cl/autorizadorventa")
        String codSucursal)
        throws AutorizadorVentaWebException
    ;

}
