
package cl.imperial.estacionmantencion.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstacionMantencionWeb", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstacionMantencionWeb {


    /**
     * 
     * @return
     *     returns cl.imperial.estacionmantencion.ws.BuscaempBcaResult
     * @throws EstacionMantencionWebException
     */
    @WebMethod
    @WebResult(name = "buscaempBcaResult", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
    @RequestWrapper(localName = "buscaempBca", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscaempBca")
    @ResponseWrapper(localName = "buscaempBcaResponse", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscaempBcaResponse")
    @Action(input = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaempBcaRequest", output = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaempBcaResponse", fault = {
        @FaultAction(className = EstacionMantencionWebException.class, value = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaempBca/Fault/EstacionMantencionWebException")
    })
    public BuscaempBcaResult buscaempBca()
        throws EstacionMantencionWebException
    ;

    /**
     * 
     * @param usuCodigo
     * @return
     *     returns cl.imperial.estacionmantencion.ws.BuscausuBcaResult
     * @throws EstacionMantencionWebException
     */
    @WebMethod
    @WebResult(name = "buscausuBcaResult", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
    @RequestWrapper(localName = "buscausuBca", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscausuBca")
    @ResponseWrapper(localName = "buscausuBcaResponse", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscausuBcaResponse")
    @Action(input = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscausuBcaRequest", output = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscausuBcaResponse", fault = {
        @FaultAction(className = EstacionMantencionWebException.class, value = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscausuBca/Fault/EstacionMantencionWebException")
    })
    public BuscausuBcaResult buscausuBca(
        @WebParam(name = "usuCodigo", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String usuCodigo)
        throws EstacionMantencionWebException
    ;

    /**
     * 
     * @param est
     * @return
     *     returns cl.imperial.estacionmantencion.ws.BuscaestBcaResult
     * @throws EstacionMantencionWebException
     */
    @WebMethod
    @WebResult(name = "buscaestBcaResult", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
    @RequestWrapper(localName = "buscaestBca", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscaestBca")
    @ResponseWrapper(localName = "buscaestBcaResponse", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.BuscaestBcaResponse")
    @Action(input = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaestBcaRequest", output = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaestBcaResponse", fault = {
        @FaultAction(className = EstacionMantencionWebException.class, value = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/buscaestBca/Fault/EstacionMantencionWebException")
    })
    public BuscaestBcaResult buscaestBca(
        @WebParam(name = "est", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String est)
        throws EstacionMantencionWebException
    ;

    /**
     * 
     * @param est
     * @return
     *     returns cl.imperial.estacionmantencion.ws.EliminaestEliResult
     * @throws EstacionMantencionWebException
     */
    @WebMethod
    @WebResult(name = "eliminaestEliResult", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
    @RequestWrapper(localName = "eliminaestEli", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.EliminaestEli")
    @ResponseWrapper(localName = "eliminaestEliResponse", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.EliminaestEliResponse")
    @Action(input = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/eliminaestEliRequest", output = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/eliminaestEliResponse", fault = {
        @FaultAction(className = EstacionMantencionWebException.class, value = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/eliminaestEli/Fault/EstacionMantencionWebException")
    })
    public EliminaestEliResult eliminaestEli(
        @WebParam(name = "est", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String est)
        throws EstacionMantencionWebException
    ;

    /**
     * 
     * @param sucran
     * @param est
     * @param emp
     * @param estran
     * @param tipoest
     * @param desc
     * @return
     *     returns cl.imperial.estacionmantencion.ws.IngresaestInsResult
     * @throws EstacionMantencionWebException
     */
    @WebMethod
    @WebResult(name = "ingresaestInsResult", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
    @RequestWrapper(localName = "ingresaestIns", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.IngresaestIns")
    @ResponseWrapper(localName = "ingresaestInsResponse", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", className = "cl.imperial.estacionmantencion.ws.IngresaestInsResponse")
    @Action(input = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/ingresaestInsRequest", output = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/ingresaestInsResponse", fault = {
        @FaultAction(className = EstacionMantencionWebException.class, value = "http://ws.estacionmantencion.imperial.cl/estacionmantencion/EstacionMantencionWeb/ingresaestIns/Fault/EstacionMantencionWebException")
    })
    public IngresaestInsResult ingresaestIns(
        @WebParam(name = "est", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String est,
        @WebParam(name = "emp", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String emp,
        @WebParam(name = "tipoest", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String tipoest,
        @WebParam(name = "desc", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String desc,
        @WebParam(name = "sucran", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String sucran,
        @WebParam(name = "estran", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion")
        String estran)
        throws EstacionMantencionWebException
    ;

}
