
package cl.imperial.estacionmantencion.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstacionMantencionWebService", targetNamespace = "http://ws.estacionmantencion.imperial.cl/estacionmantencion", wsdlLocation = "EstacionMantencionWebService.wsdl")
public class EstacionMantencionWebService
    extends Service
{

    private final static URL ESTACIONMANTENCIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTACIONMANTENCIONWEBSERVICE_EXCEPTION;
    private final static QName ESTACIONMANTENCIONWEBSERVICE_QNAME = new QName("http://ws.estacionmantencion.imperial.cl/estacionmantencion", "EstacionMantencionWebService");

    static {
        ESTACIONMANTENCIONWEBSERVICE_WSDL_LOCATION = cl.imperial.estacionmantencion.ws.EstacionMantencionWebService.class.getResource("EstacionMantencionWebService.wsdl");
        WebServiceException e = null;
        if (ESTACIONMANTENCIONWEBSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'EstacionMantencionWebService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ESTACIONMANTENCIONWEBSERVICE_EXCEPTION = e;
    }

    public EstacionMantencionWebService() {
        super(__getWsdlLocation(), ESTACIONMANTENCIONWEBSERVICE_QNAME);
    }

    public EstacionMantencionWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTACIONMANTENCIONWEBSERVICE_QNAME, features);
    }

    public EstacionMantencionWebService(URL wsdlLocation) {
        super(wsdlLocation, ESTACIONMANTENCIONWEBSERVICE_QNAME);
    }

    public EstacionMantencionWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTACIONMANTENCIONWEBSERVICE_QNAME, features);
    }

    public EstacionMantencionWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstacionMantencionWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstacionMantencionWeb
     */
    @WebEndpoint(name = "EstacionMantencionWebPort")
    public EstacionMantencionWeb getEstacionMantencionWebPort() {
        return super.getPort(new QName("http://ws.estacionmantencion.imperial.cl/estacionmantencion", "EstacionMantencionWebPort"), EstacionMantencionWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstacionMantencionWeb
     */
    @WebEndpoint(name = "EstacionMantencionWebPort")
    public EstacionMantencionWeb getEstacionMantencionWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.estacionmantencion.imperial.cl/estacionmantencion", "EstacionMantencionWebPort"), EstacionMantencionWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTACIONMANTENCIONWEBSERVICE_EXCEPTION!= null) {
            throw ESTACIONMANTENCIONWEBSERVICE_EXCEPTION;
        }
        return ESTACIONMANTENCIONWEBSERVICE_WSDL_LOCATION;
    }

}
