/*
 * Source: EscanerProductoWebException.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.escanerproducto.ws;

import java.sql.SQLException;
import javax.xml.ws.WebFault;

/**
 * Thrown when an error occurs during the execution a Web Service method.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@WebFault(name = "faultinfo")
public class EscanerProductoWebException extends Exception
{
    private static final long serialVersionUID = 1L;
    private final WebFaultInfo webFaultInfo;

    /**
     * Constructs a new {@code EscanerProductoWebException} with cause and subject.
     *
     * @param cause the cause of the exception.
     * @param subject the subject of the exception.
     */
    public EscanerProductoWebException(final Throwable cause, final String subject)
    {
        // Initialize super with cause message (if any)
        super(cause != null ? cause.getMessage() : null);

        // Create WebFaultInfo with subject
        webFaultInfo = new WebFaultInfo();
        webFaultInfo.setSubject(subject);

        // Store SQLException in WebFaultInfo
        if (cause instanceof SQLException) {
            final SQLException sqlex = (SQLException) cause;
            webFaultInfo.setErrorCode(sqlex.getErrorCode());
            webFaultInfo.setSqlState(sqlex.getSQLState());
        }
    }

    /**
     * Returns the detailed information of the Web Service fault.
     *
     * @return the detailed information of the Web Service fault.
     */
    public WebFaultInfo getFaultInfo()
    {
        return webFaultInfo;
    }
}
