/*
 * Source: EscanerProductoWeb.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.escanerproducto.ws;

import java.sql.SQLException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import javax.transaction.UserTransaction;

/**
 * The {@code EscanerProducto} Web Service.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@WebService(targetNamespace = EscanerProductoWeb.TNS)
public class EscanerProductoWeb
{
    /** The Target Namespace of the Web Service. */
    public static final String TNS = "http://ws.escanerproducto.imperial.cl/escanerproducto";

    /** The Logger of the Web Service. */
    private static final Logger logger =
        Logger.getLogger(EscanerProductoWeb.class.getName());

    /** The User Transaction of the Web Service. */
    @Resource(name = "userTransaction")
    private UserTransaction userTransaction;

    /** The Data Source of the Web Service. */
    @Resource(name = "EscanerProductoDataSource")
    private DataSource dataSource;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code EscanerProductoWeb} instance.
     */
    public EscanerProductoWeb()
    {
    }

    //--------------------------------------------------------------------------
    //-- WebService Methods ----------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code Escaner$GrabaValeTranstorio}.
     *
     * @param  vxmlproductos {@code vXmlProductos varchar}.
     * @param  vcodEmp {@code vCod_Emp varchar(20)}.
     * @param  vusuario {@code vUsuario varchar(50)}.
     * @param  vtipodoc {@code vTipoDoc varchar(3)}.
     * @param  vcodEntidad {@code vCod_Entidad varchar(40)}.
     * @param  vcodSucursal {@code vCod_Sucursal varchar(3)}.
     * @param  vcodLista {@code vCod_Lista varchar(3)}.
     * @param  vestacion {@code vEstacion varchar(30)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EscanerProductoWebException if an error occurs.
     */
    @WebMethod(operationName = "grabavaletranstorio")
    @WebResult(name = "grabavaletranstorioResult", targetNamespace = TNS)
    public GrabavaletranstorioResult grabavaletranstorio(
        @WebParam(name = "vxmlproductos", targetNamespace = TNS) final String vxmlproductos,
        @WebParam(name = "vcodEmp", targetNamespace = TNS) final String vcodEmp,
        @WebParam(name = "vusuario", targetNamespace = TNS) final String vusuario,
        @WebParam(name = "vtipodoc", targetNamespace = TNS) final String vtipodoc,
        @WebParam(name = "vcodEntidad", targetNamespace = TNS) final String vcodEntidad,
        @WebParam(name = "vcodSucursal", targetNamespace = TNS) final String vcodSucursal,
        @WebParam(name = "vcodLista", targetNamespace = TNS) final String vcodLista,
        @WebParam(name = "vestacion", targetNamespace = TNS) final String vestacion)
        throws EscanerProductoWebException
    {
        final GrabavaletranstorioResult result;
        try {
            getUserTransaction().begin();
            try {
                result = GrabavaletranstorioCaller.execute(getDataSource(), vxmlproductos, vcodEmp, vusuario, vtipodoc, vcodEntidad, vcodSucursal, vcodLista, vestacion);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "grabavaletranstorio");
            throw new EscanerProductoWebException(thrown, "grabavaletranstorio");
        }
        return result;
    }

    /**
     * Executes procedure {@code Escaner$TraeLecturaScan}.
     *
     * @param  vcodigo {@code vCodigo varchar(20)}.
     * @param  vtipo {@code vTipo varchar(5)}.
     * @param  vcodLista {@code vCod_lista varchar(3)}.
     * @param  vcodEmp {@code vCod_Emp varchar(20)}.
     * @param  vcodEntidad {@code vCod_Entidad varchar(13)}.
     * @param  vcodSucursal {@code vCod_Sucursal varchar(3)}.
     * @param  vtipoDoc {@code vTipo_Doc varchar(3)}.
     * @return the output parameters and result sets of the procedure.
     * @throws EscanerProductoWebException if an error occurs.
     */
    @WebMethod(operationName = "traelecturascan")
    @WebResult(name = "traelecturascanResult", targetNamespace = TNS)
    public TraelecturascanResult traelecturascan(
        @WebParam(name = "vcodigo", targetNamespace = TNS) final String vcodigo,
        @WebParam(name = "vtipo", targetNamespace = TNS) final String vtipo,
        @WebParam(name = "vcodLista", targetNamespace = TNS) final String vcodLista,
        @WebParam(name = "vcodEmp", targetNamespace = TNS) final String vcodEmp,
        @WebParam(name = "vcodEntidad", targetNamespace = TNS) final String vcodEntidad,
        @WebParam(name = "vcodSucursal", targetNamespace = TNS) final String vcodSucursal,
        @WebParam(name = "vtipoDoc", targetNamespace = TNS) final String vtipoDoc)
        throws EscanerProductoWebException
    {
        final TraelecturascanResult result;
        try {
            getUserTransaction().begin();
            try {
                result = TraelecturascanCaller.execute(getDataSource(), vcodigo, vtipo, vcodLista, vcodEmp, vcodEntidad, vcodSucursal, vtipoDoc);
            } catch (final Throwable callerThrowable) {
                getUserTransaction().rollback();
                throw callerThrowable;
            }
            getUserTransaction().commit();
        } catch (final Throwable thrown) {
            logError(thrown, "traelecturascan");
            throw new EscanerProductoWebException(thrown, "traelecturascan");
        }
        return result;
    }

    //--------------------------------------------------------------------------
    //-- JNDI Methods ----------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the user transaction of the WebService.
     *
     * @return the user transaction of the WebService.
     * @throws NamingException if a JNDI error occurs.
     */
    private UserTransaction getUserTransaction()
        throws NamingException
    {
        if (userTransaction == null) {
            final InitialContext context = new InitialContext();
            try {
                userTransaction = (UserTransaction) context.lookup("java:comp/UserTransaction");
            } finally {
                context.close();
            }
        }
        return userTransaction;
    }

    /**
     * Returns the data source of the WebService.
     *
     * @return the data source of the WebService.
     * @throws NamingException if a JNDI error occurs.
     */
    private DataSource getDataSource()
        throws NamingException
    {
        if (dataSource == null) {
            final InitialContext context = new InitialContext();
            try {
                dataSource = (DataSource) context.lookup("java:comp/env/EscanerProductoDataSource");
            } finally {
                context.close();
            }
        }
        return dataSource;
    }

    //--------------------------------------------------------------------------
    //-- Error Methods ---------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Logs a method error with associated throwable information.
     *
     * @param thrown the throwable associated with the error.
     * @param methodName the name of method that threw the error.
     */
    private void logError(final Throwable thrown, final String methodName)
    {
        if (thrown instanceof SQLException) {
            logSqlError((SQLException) thrown, methodName);
        } else {
            final String fullName = getClass().getName() + '#' + methodName;
            logger.log(Level.SEVERE, "Error executing " + fullName, thrown);
        }
    }

    /**
     * Logs a method error with associated SQLException information.
     *
     * @param  sqlex the SQLException associated with the error.
     * @param  methodName the name of method that threw the error.
     * @throws NullPointerException if {@code sqlex} is {@code null}.
     */
    private void logSqlError(final SQLException sqlex, final String methodName)
    {
        // Compute full method name and obtain SQL properties
        final String fullName = getClass().getName() + '#' + methodName;
        final String sqlState = sqlex.getSQLState();
        final int sqlErrorCode = sqlex.getErrorCode();

        // Obtain all error messages of SQLException
        final StringBuilder sb = new StringBuilder(200);
        final Iterator<Throwable> iter = sqlex.iterator();
        while (iter.hasNext()) {
            final Throwable cause = iter.next();
            if (sb.length() > 0) sb.append(": ");
            final String msg = cause.getMessage();
            sb.append(msg != null ? msg : cause.toString());
        }
        final String sqlMessages = sb.toString();

        // Log error including full method name and SQL properties
        final String sqlProps = ": (" + sqlState + ',' + sqlErrorCode + ") ";
        logger.severe("Error executing " + fullName + sqlProps + sqlMessages);
    }
}
