/*
 * Source: GrabavaletranstorioResult.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.escanerproducto.ws;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Results of procedure {@code Escaner$GrabaValeTranstorio}.
 *
 * <pre>
 * Nro_Interno    int      Output
 * Error_Message  varchar  Output
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "grabavaletranstorioResult")
@XmlType(name = "GrabavaletranstorioResult")
public class GrabavaletranstorioResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private Integer nroInterno;
    private String errorMessage;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code GrabavaletranstorioResult} instance.
     */
    public GrabavaletranstorioResult()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code nroInterno}.
     *
     * @return the current value of the property.
     */
    public Integer getNroInterno()
    {
        return nroInterno;
    }

    /**
     * Changes the value of property {@code nroInterno}.
     *
     * @param value the new value of the property.
     */
    public void setNroInterno(final Integer value)
    {
        this.nroInterno = value;
    }

    /**
     * Returns the value of property {@code errorMessage}.
     *
     * @return the current value of the property.
     */
    public String getErrorMessage()
    {
        return errorMessage;
    }

    /**
     * Changes the value of property {@code errorMessage}.
     *
     * @param value the new value of the property.
     */
    public void setErrorMessage(final String value)
    {
        this.errorMessage = value;
    }
}
