/*
 * Source: TraelecturascanProducto.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.escanerproducto.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code PRODUCTO} of procedure {@code Escaner$TraeLecturaScan}.
 *
 * <pre>
 * #ResultSet PRODUCTO PRODUCTOS
 *   #Column  COD_RAPIDO         NVARCHAR
 *   #Column  COD_PRODUCTO       NVARCHAR
 *   #Column  DESCRIPCION        NVARCHAR
 *   #Column  PRECIO_BRUTO       NVARCHAR
 *   #Column  DESCUENTO          NVARCHAR
 *   #Column  CANTIDAD_EMBALAJE  NVARCHAR
 *   #Column  COD_UNIMED         NVARCHAR
 *   #Column  CANTIDAD           NVARCHAR
 *   #Column  TIPO               NVARCHAR
 *   #Column  CODE               NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "traelecturascanProducto")
@XmlType(name = "TraelecturascanProducto")
public class TraelecturascanProducto implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String codRapido;
    private String codProducto;
    private String descripcion;
    private String precioBruto;
    private String descuento;
    private String cantidadEmbalaje;
    private String codUnimed;
    private String cantidad;
    private String tipo;
    private String code;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code TraelecturascanProducto} instance.
     */
    public TraelecturascanProducto()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code codRapido}.
     *
     * @return the current value of the property.
     */
    public String getCodRapido()
    {
        return codRapido;
    }

    /**
     * Changes the value of property {@code codRapido}.
     *
     * @param value the new value of the property.
     */
    public void setCodRapido(final String value)
    {
        this.codRapido = value;
    }

    /**
     * Returns the value of property {@code codProducto}.
     *
     * @return the current value of the property.
     */
    public String getCodProducto()
    {
        return codProducto;
    }

    /**
     * Changes the value of property {@code codProducto}.
     *
     * @param value the new value of the property.
     */
    public void setCodProducto(final String value)
    {
        this.codProducto = value;
    }

    /**
     * Returns the value of property {@code descripcion}.
     *
     * @return the current value of the property.
     */
    public String getDescripcion()
    {
        return descripcion;
    }

    /**
     * Changes the value of property {@code descripcion}.
     *
     * @param value the new value of the property.
     */
    public void setDescripcion(final String value)
    {
        this.descripcion = value;
    }

    /**
     * Returns the value of property {@code precioBruto}.
     *
     * @return the current value of the property.
     */
    public String getPrecioBruto()
    {
        return precioBruto;
    }

    /**
     * Changes the value of property {@code precioBruto}.
     *
     * @param value the new value of the property.
     */
    public void setPrecioBruto(final String value)
    {
        this.precioBruto = value;
    }

    /**
     * Returns the value of property {@code descuento}.
     *
     * @return the current value of the property.
     */
    public String getDescuento()
    {
        return descuento;
    }

    /**
     * Changes the value of property {@code descuento}.
     *
     * @param value the new value of the property.
     */
    public void setDescuento(final String value)
    {
        this.descuento = value;
    }

    /**
     * Returns the value of property {@code cantidadEmbalaje}.
     *
     * @return the current value of the property.
     */
    public String getCantidadEmbalaje()
    {
        return cantidadEmbalaje;
    }

    /**
     * Changes the value of property {@code cantidadEmbalaje}.
     *
     * @param value the new value of the property.
     */
    public void setCantidadEmbalaje(final String value)
    {
        this.cantidadEmbalaje = value;
    }

    /**
     * Returns the value of property {@code codUnimed}.
     *
     * @return the current value of the property.
     */
    public String getCodUnimed()
    {
        return codUnimed;
    }

    /**
     * Changes the value of property {@code codUnimed}.
     *
     * @param value the new value of the property.
     */
    public void setCodUnimed(final String value)
    {
        this.codUnimed = value;
    }

    /**
     * Returns the value of property {@code cantidad}.
     *
     * @return the current value of the property.
     */
    public String getCantidad()
    {
        return cantidad;
    }

    /**
     * Changes the value of property {@code cantidad}.
     *
     * @param value the new value of the property.
     */
    public void setCantidad(final String value)
    {
        this.cantidad = value;
    }

    /**
     * Returns the value of property {@code tipo}.
     *
     * @return the current value of the property.
     */
    public String getTipo()
    {
        return tipo;
    }

    /**
     * Changes the value of property {@code tipo}.
     *
     * @param value the new value of the property.
     */
    public void setTipo(final String value)
    {
        this.tipo = value;
    }

    /**
     * Returns the value of property {@code code}.
     *
     * @return the current value of the property.
     */
    public String getCode()
    {
        return code;
    }

    /**
     * Changes the value of property {@code code}.
     *
     * @param value the new value of the property.
     */
    public void setCode(final String value)
    {
        this.code = value;
    }
}
