
package cl.imperial.sencillosolicitud.ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SencilloSolicitudWeb", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SencilloSolicitudWeb {


    /**
     * 
     * @param estado
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.TraedenmonBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "traedenmonBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "traedenmonBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.TraedenmonBca")
    @ResponseWrapper(localName = "traedenmonBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.TraedenmonBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traedenmonBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traedenmonBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traedenmonBca/Fault/SencilloSolicitudWebException")
    })
    public TraedenmonBcaResult traedenmonBca(
        @WebParam(name = "estado", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String estado)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param cierre
     * @param montoEfe
     * @param tipoTran
     * @param detefectivo
     * @param detdoctos
     * @param codEmp
     * @param montoDoc
     * @param idBandejapos
     * @param codUsurecibe
     * @param usuario
     * @param estacion
     * @param sencillo
     * @param tipoEnvio
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.GrabaenviobanInsResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "grabaenviobanInsResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "grabaenviobanIns", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.GrabaenviobanIns")
    @ResponseWrapper(localName = "grabaenviobanInsResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.GrabaenviobanInsResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/grabaenviobanInsRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/grabaenviobanInsResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/grabaenviobanIns/Fault/SencilloSolicitudWebException")
    })
    public GrabaenviobanInsResult grabaenviobanIns(
        @WebParam(name = "tipoTran", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String tipoTran,
        @WebParam(name = "montoEfe", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        BigDecimal montoEfe,
        @WebParam(name = "montoDoc", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        BigDecimal montoDoc,
        @WebParam(name = "codEmp", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codEmp,
        @WebParam(name = "detefectivo", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String detefectivo,
        @WebParam(name = "detdoctos", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String detdoctos,
        @WebParam(name = "sencillo", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String sencillo,
        @WebParam(name = "usuario", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String usuario,
        @WebParam(name = "estacion", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String estacion,
        @WebParam(name = "codUsurecibe", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codUsurecibe,
        @WebParam(name = "cierre", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String cierre,
        @WebParam(name = "tipoEnvio", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String tipoEnvio,
        @WebParam(name = "idBandejapos", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String idBandejapos)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param codEmp
     * @param cajero
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.BuscabanusutieBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "buscabanusutieBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "buscabanusutieBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscabanusutieBca")
    @ResponseWrapper(localName = "buscabanusutieBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscabanusutieBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscabanusutieBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscabanusutieBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscabanusutieBca/Fault/SencilloSolicitudWebException")
    })
    public BuscabanusutieBcaResult buscabanusutieBca(
        @WebParam(name = "codEmp", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codEmp,
        @WebParam(name = "cajero", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String cajero)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param estacion
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.BuscaempresaxestacionBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "buscaempresaxestacionBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "buscaempresaxestacionBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscaempresaxestacionBca")
    @ResponseWrapper(localName = "buscaempresaxestacionBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscaempresaxestacionBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaempresaxestacionBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaempresaxestacionBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaempresaxestacionBca/Fault/SencilloSolicitudWebException")
    })
    public BuscaempresaxestacionBcaResult buscaempresaxestacionBca(
        @WebParam(name = "estacion", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String estacion)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param parametro
     * @param valor
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.BuscausuariosvaBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "buscausuariosvaBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "buscausuariosvaBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscausuariosvaBca")
    @ResponseWrapper(localName = "buscausuariosvaBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscausuariosvaBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscausuariosvaBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscausuariosvaBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscausuariosvaBca/Fault/SencilloSolicitudWebException")
    })
    public BuscausuariosvaBcaResult buscausuariosvaBca(
        @WebParam(name = "valor", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String valor,
        @WebParam(name = "parametro", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String parametro)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param codUsuario
     * @param codVendedor
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.MantusuariosearchBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "mantusuariosearchBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "mantusuariosearchBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.MantusuariosearchBca")
    @ResponseWrapper(localName = "mantusuariosearchBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.MantusuariosearchBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/mantusuariosearchBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/mantusuariosearchBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/mantusuariosearchBca/Fault/SencilloSolicitudWebException")
    })
    public MantusuariosearchBcaResult mantusuariosearchBca(
        @WebParam(name = "codVendedor", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codVendedor,
        @WebParam(name = "codUsuario", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codUsuario)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param tipoTran
     * @param codEmp
     * @param usuario
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.BuscaultimovoucherBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "buscaultimovoucherBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "buscaultimovoucherBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscaultimovoucherBca")
    @ResponseWrapper(localName = "buscaultimovoucherBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.BuscaultimovoucherBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaultimovoucherBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaultimovoucherBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/buscaultimovoucherBca/Fault/SencilloSolicitudWebException")
    })
    public BuscaultimovoucherBcaResult buscaultimovoucherBca(
        @WebParam(name = "tipoTran", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String tipoTran,
        @WebParam(name = "codEmp", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String codEmp,
        @WebParam(name = "usuario", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        String usuario)
        throws SencilloSolicitudWebException
    ;

    /**
     * 
     * @param nroInterno
     * @return
     *     returns cl.imperial.sencillosolicitud.ws.TraesolicitudcjBcaResult
     * @throws SencilloSolicitudWebException
     */
    @WebMethod
    @WebResult(name = "traesolicitudcjBcaResult", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
    @RequestWrapper(localName = "traesolicitudcjBca", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.TraesolicitudcjBca")
    @ResponseWrapper(localName = "traesolicitudcjBcaResponse", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud", className = "cl.imperial.sencillosolicitud.ws.TraesolicitudcjBcaResponse")
    @Action(input = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traesolicitudcjBcaRequest", output = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traesolicitudcjBcaResponse", fault = {
        @FaultAction(className = SencilloSolicitudWebException.class, value = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud/SencilloSolicitudWeb/traesolicitudcjBca/Fault/SencilloSolicitudWebException")
    })
    public TraesolicitudcjBcaResult traesolicitudcjBca(
        @WebParam(name = "nroInterno", targetNamespace = "http://ws.sencillosolicitud.imperial.cl/sencillosolicitud")
        Integer nroInterno)
        throws SencilloSolicitudWebException
    ;

}
