/*
 * Source: BuscaclienterutBcaCliente.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.tipodocumento.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code CLIENTE} of procedure {@code TipoDocumento$BuscaClienteRut_bca}.
 *
 * <pre>
 * #ResultSet CLIENTE CLIENTES
 *   #Column  COD_ENTIDAD       NVARCHAR
 *   #Column  ID_CLIENTE        NVARCHAR
 *   #Column  COD_SUCURSAL      NVARCHAR
 *   #Column  RUT_CLIENTE       NVARCHAR
 *   #Column  DV_CLIENTE        NVARCHAR
 *   #Column  NOMBRE            NVARCHAR
 *   #Column  PATERNO           NVARCHAR
 *   #Column  MATERNO           NVARCHAR
 *   #Column  CLIENTE           NVARCHAR
 *   #Column  ESTADO            NVARCHAR
 *   #Column  CLI_CATEGORIA     NVARCHAR
 *   #Column  PLAZO             NVARCHAR
 *   #Column  TIPOPERSONALIDAD  NVARCHAR
 *   #Column  CREDITO           NVARCHAR
 *   #Column  LISTA_PRECIO      NVARCHAR
 *   #Column  ESTADO_CLIENTE    NVARCHAR
 *   #Column  CRED_ABIERTO_DOC  NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "buscaclienterutBcaCliente")
@XmlType(name = "BuscaclienterutBcaCliente")
public class BuscaclienterutBcaCliente implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String codEntidad;
    private String idCliente;
    private String codSucursal;
    private String rutCliente;
    private String dvCliente;
    private String nombre;
    private String paterno;
    private String materno;
    private String cliente;
    private String estado;
    private String cliCategoria;
    private String plazo;
    private String tipopersonalidad;
    private String credito;
    private String listaPrecio;
    private String estadoCliente;
    private String credAbiertoDoc;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaclienterutBcaCliente} instance.
     */
    public BuscaclienterutBcaCliente()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code codEntidad}.
     *
     * @return the current value of the property.
     */
    public String getCodEntidad()
    {
        return codEntidad;
    }

    /**
     * Changes the value of property {@code codEntidad}.
     *
     * @param value the new value of the property.
     */
    public void setCodEntidad(final String value)
    {
        this.codEntidad = value;
    }

    /**
     * Returns the value of property {@code idCliente}.
     *
     * @return the current value of the property.
     */
    public String getIdCliente()
    {
        return idCliente;
    }

    /**
     * Changes the value of property {@code idCliente}.
     *
     * @param value the new value of the property.
     */
    public void setIdCliente(final String value)
    {
        this.idCliente = value;
    }

    /**
     * Returns the value of property {@code codSucursal}.
     *
     * @return the current value of the property.
     */
    public String getCodSucursal()
    {
        return codSucursal;
    }

    /**
     * Changes the value of property {@code codSucursal}.
     *
     * @param value the new value of the property.
     */
    public void setCodSucursal(final String value)
    {
        this.codSucursal = value;
    }

    /**
     * Returns the value of property {@code rutCliente}.
     *
     * @return the current value of the property.
     */
    public String getRutCliente()
    {
        return rutCliente;
    }

    /**
     * Changes the value of property {@code rutCliente}.
     *
     * @param value the new value of the property.
     */
    public void setRutCliente(final String value)
    {
        this.rutCliente = value;
    }

    /**
     * Returns the value of property {@code dvCliente}.
     *
     * @return the current value of the property.
     */
    public String getDvCliente()
    {
        return dvCliente;
    }

    /**
     * Changes the value of property {@code dvCliente}.
     *
     * @param value the new value of the property.
     */
    public void setDvCliente(final String value)
    {
        this.dvCliente = value;
    }

    /**
     * Returns the value of property {@code nombre}.
     *
     * @return the current value of the property.
     */
    public String getNombre()
    {
        return nombre;
    }

    /**
     * Changes the value of property {@code nombre}.
     *
     * @param value the new value of the property.
     */
    public void setNombre(final String value)
    {
        this.nombre = value;
    }

    /**
     * Returns the value of property {@code paterno}.
     *
     * @return the current value of the property.
     */
    public String getPaterno()
    {
        return paterno;
    }

    /**
     * Changes the value of property {@code paterno}.
     *
     * @param value the new value of the property.
     */
    public void setPaterno(final String value)
    {
        this.paterno = value;
    }

    /**
     * Returns the value of property {@code materno}.
     *
     * @return the current value of the property.
     */
    public String getMaterno()
    {
        return materno;
    }

    /**
     * Changes the value of property {@code materno}.
     *
     * @param value the new value of the property.
     */
    public void setMaterno(final String value)
    {
        this.materno = value;
    }

    /**
     * Returns the value of property {@code cliente}.
     *
     * @return the current value of the property.
     */
    public String getCliente()
    {
        return cliente;
    }

    /**
     * Changes the value of property {@code cliente}.
     *
     * @param value the new value of the property.
     */
    public void setCliente(final String value)
    {
        this.cliente = value;
    }

    /**
     * Returns the value of property {@code estado}.
     *
     * @return the current value of the property.
     */
    public String getEstado()
    {
        return estado;
    }

    /**
     * Changes the value of property {@code estado}.
     *
     * @param value the new value of the property.
     */
    public void setEstado(final String value)
    {
        this.estado = value;
    }

    /**
     * Returns the value of property {@code cliCategoria}.
     *
     * @return the current value of the property.
     */
    public String getCliCategoria()
    {
        return cliCategoria;
    }

    /**
     * Changes the value of property {@code cliCategoria}.
     *
     * @param value the new value of the property.
     */
    public void setCliCategoria(final String value)
    {
        this.cliCategoria = value;
    }

    /**
     * Returns the value of property {@code plazo}.
     *
     * @return the current value of the property.
     */
    public String getPlazo()
    {
        return plazo;
    }

    /**
     * Changes the value of property {@code plazo}.
     *
     * @param value the new value of the property.
     */
    public void setPlazo(final String value)
    {
        this.plazo = value;
    }

    /**
     * Returns the value of property {@code tipopersonalidad}.
     *
     * @return the current value of the property.
     */
    public String getTipopersonalidad()
    {
        return tipopersonalidad;
    }

    /**
     * Changes the value of property {@code tipopersonalidad}.
     *
     * @param value the new value of the property.
     */
    public void setTipopersonalidad(final String value)
    {
        this.tipopersonalidad = value;
    }

    /**
     * Returns the value of property {@code credito}.
     *
     * @return the current value of the property.
     */
    public String getCredito()
    {
        return credito;
    }

    /**
     * Changes the value of property {@code credito}.
     *
     * @param value the new value of the property.
     */
    public void setCredito(final String value)
    {
        this.credito = value;
    }

    /**
     * Returns the value of property {@code listaPrecio}.
     *
     * @return the current value of the property.
     */
    public String getListaPrecio()
    {
        return listaPrecio;
    }

    /**
     * Changes the value of property {@code listaPrecio}.
     *
     * @param value the new value of the property.
     */
    public void setListaPrecio(final String value)
    {
        this.listaPrecio = value;
    }

    /**
     * Returns the value of property {@code estadoCliente}.
     *
     * @return the current value of the property.
     */
    public String getEstadoCliente()
    {
        return estadoCliente;
    }

    /**
     * Changes the value of property {@code estadoCliente}.
     *
     * @param value the new value of the property.
     */
    public void setEstadoCliente(final String value)
    {
        this.estadoCliente = value;
    }

    /**
     * Returns the value of property {@code credAbiertoDoc}.
     *
     * @return the current value of the property.
     */
    public String getCredAbiertoDoc()
    {
        return credAbiertoDoc;
    }

    /**
     * Changes the value of property {@code credAbiertoDoc}.
     *
     * @param value the new value of the property.
     */
    public void setCredAbiertoDoc(final String value)
    {
        this.credAbiertoDoc = value;
    }
}
