/*
 * Source: BuscaclienterutBcaCaller.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.autorizadorventa.ws;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * Caller of procedure {@code AutorizadorVenta$BuscaClienteRut_bca}.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
public class BuscaclienterutBcaCaller extends ProcedureCaller
{
    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaclienterutBcaCaller} instance.
     */
    public BuscaclienterutBcaCaller()
    {
    }

    //--------------------------------------------------------------------------
    //-- Execute Methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code AutorizadorVenta$BuscaClienteRut_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  rutCliente {@code RUT_CLIENTE varchar(13)}.
     * @param  codEntidad {@code COD_ENTIDAD varchar(13)}.
     * @param  codSucursal {@code COD_SUCURSAL varchar(3)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscaclienterutBcaResult executeProc(final DataSource dataSource, String rutCliente, String codEntidad, String codSucursal)
        throws SQLException
    {
        try (final Connection conn = dataSource.getConnection()) {
            return executeProc(conn, rutCliente, codEntidad, codSucursal);
        }
    }

    /**
     * Executes procedure {@code AutorizadorVenta$BuscaClienteRut_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  rutCliente {@code RUT_CLIENTE varchar(13)}.
     * @param  codEntidad {@code COD_ENTIDAD varchar(13)}.
     * @param  codSucursal {@code COD_SUCURSAL varchar(3)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscaclienterutBcaResult executeProc(final Connection conn, String rutCliente, String codEntidad, String codSucursal)
        throws SQLException
    {
        final BuscaclienterutBcaResult result = createProcResult();
        final String jdbcURL = getJdbcURL(conn);
        if (jdbcURL.startsWith("jdbc:oracle:")) {
            try (final CallableStatement call = prepareCall(conn, "{call AutorizadorVenta$BuscaClienteRut_bca(?,?,?,?,?)}")) {
                call.setString(1, rutCliente);
                call.setString(2, codEntidad);
                call.setString(3, codSucursal);
                call.registerOutParameter(4, Types.NVARCHAR);
                call.registerOutParameter(5, ORACLE_CURSOR);
                call.execute();
                result.setErrorMessage(call.getString(4));
                result.setClientes(readClientes((ResultSet) call.getObject(5)));
            }
        } else if (jdbcURL.startsWith("jdbc:postgresql:")) {
            try (final CallableStatement call = prepareCall(conn, "{call AutorizadorVenta$BuscaClienteRut_bca(?,?,?,?,?)}")) {
                call.setString(1, rutCliente);
                call.setString(2, codEntidad);
                call.setString(3, codSucursal);
                call.registerOutParameter(4, Types.NVARCHAR);
                call.registerOutParameter(5, Types.OTHER);
                call.execute();
                result.setErrorMessage(call.getString(4));
                result.setClientes(readClientes((ResultSet) call.getObject(5)));
            }
        } else {
            try (final CallableStatement call = prepareCall(conn, "{call AutorizadorVenta$BuscaClienteRut_bca(?,?,?,?)}")) {
                call.setString(1, rutCliente);
                call.setString(2, codEntidad);
                call.setString(3, codSucursal);
                call.registerOutParameter(4, Types.NVARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset) {
                        updateCount = call.getUpdateCount();
                    } else if (result.getClientes() == null) {
                        result.setClientes(readClientes(call.getResultSet()));
                    } else {
                        unexpectedResultSet(call.getResultSet());
                    }
                    haveRset = call.getMoreResults();
                }
                result.setErrorMessage(call.getString(4));
            }
        }
        return result;
    }

    /**
     * Creates and returns a new instance of {@code BuscaclienterutBcaResult}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscaclienterutBcaResult}.
     *
     * @return a new {@code BuscaclienterutBcaResult} instance.
     */
    protected BuscaclienterutBcaResult createProcResult()
    {
        return new BuscaclienterutBcaResult();
    }

    //--------------------------------------------------------------------------
    //-- BuscaclienterutBcaCliente ResultSet Methods ---------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts a result set to an array of {@code BuscaclienterutBcaCliente}.
     *
     * @param  resultSet the result set to convert (can be null).
     * @return an array of {@code BuscaclienterutBcaCliente} or null.
     * @throws SQLException if an SQL error occurs.
     */
    protected List<BuscaclienterutBcaCliente> readClientes(final ResultSet resultSet)
        throws SQLException
    {
        if (resultSet == null)
            return null;
        try {
            // Obtain ordinal (index) numbers of result columns
            final int cRutCliente = resultSet.findColumn("RUT_CLIENTE");
            final int cDvCliente = resultSet.findColumn("DV_CLIENTE");
            final int cCodEntidad = resultSet.findColumn("COD_ENTIDAD");
            final int cCodSucursal = resultSet.findColumn("COD_SUCURSAL");
            final int cCliente = resultSet.findColumn("CLIENTE");
            final int cValido = resultSet.findColumn("VALIDO");
            final int cEstado = resultSet.findColumn("ESTADO");

            // Convert result rows to an array of "BuscaclienterutBcaCliente"
            final List<BuscaclienterutBcaCliente> list = new ArrayList<>();
            while (resultSet.next()) {
                final BuscaclienterutBcaCliente item = createCliente();
                item.setRutCliente(resultSet.getString(cRutCliente));
                item.setDvCliente(resultSet.getString(cDvCliente));
                item.setCodEntidad(resultSet.getString(cCodEntidad));
                item.setCodSucursal(resultSet.getString(cCodSucursal));
                item.setCliente(resultSet.getString(cCliente));
                item.setValido(resultSet.getString(cValido));
                item.setEstado(resultSet.getString(cEstado));
                if (filterCliente(item)) list.add(item);
            }
            return list;
        } finally {
            resultSet.close();
        }
    }

    /**
     * Creates and returns a new instance of {@code BuscaclienterutBcaCliente}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscaclienterutBcaCliente}.
     *
     * @return a new {@code BuscaclienterutBcaCliente} instance.
     */
    protected BuscaclienterutBcaCliente createCliente()
    {
        return new BuscaclienterutBcaCliente();
    }

    /**
     * Returns {@code true} if supplied item should be added to result set.
     * <p>
     * Can be overridden to select which items are added to the result set.
     *
     * @param  item the {@code BuscaclienterutBcaCliente} to be checked.
     * @return {@code true} if {@code item} should be added to result set.
     * @throws NullPointerException if {@code item} is {@code null}.
     */
    protected boolean filterCliente(final BuscaclienterutBcaCliente item)
    {
        return true;
    }

    //--------------------------------------------------------------------------
    //-- Static Methods --------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code AutorizadorVenta$BuscaClienteRut_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  rutCliente {@code RUT_CLIENTE varchar(13)}.
     * @param  codEntidad {@code COD_ENTIDAD varchar(13)}.
     * @param  codSucursal {@code COD_SUCURSAL varchar(3)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscaclienterutBcaResult execute(final DataSource dataSource, String rutCliente, String codEntidad, String codSucursal)
        throws SQLException
    {
        return new BuscaclienterutBcaCaller().executeProc(dataSource, rutCliente, codEntidad, codSucursal);
    }

    /**
     * Executes procedure {@code AutorizadorVenta$BuscaClienteRut_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  rutCliente {@code RUT_CLIENTE varchar(13)}.
     * @param  codEntidad {@code COD_ENTIDAD varchar(13)}.
     * @param  codSucursal {@code COD_SUCURSAL varchar(3)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscaclienterutBcaResult execute(final Connection conn, String rutCliente, String codEntidad, String codSucursal)
        throws SQLException
    {
        return new BuscaclienterutBcaCaller().executeProc(conn, rutCliente, codEntidad, codSucursal);
    }
}
