/*
 * Source: BuscaclienterutBcaCliente.java - Generated by OBCOM SQL Wizard 1.160
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.autorizadorventa.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code CLIENTE} of procedure {@code AutorizadorVenta$BuscaClienteRut_bca}.
 *
 * <pre>
 * #ResultSet CLIENTE CLIENTES
 *   #Column  RUT_CLIENTE   NVARCHAR
 *   #Column  DV_CLIENTE    NVARCHAR
 *   #Column  COD_ENTIDAD   NVARCHAR
 *   #Column  COD_SUCURSAL  NVARCHAR
 *   #Column  CLIENTE       NVARCHAR
 *   #Column  VALIDO        NVARCHAR
 *   #Column  ESTADO        NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "buscaclienterutBcaCliente")
@XmlType(name = "BuscaclienterutBcaCliente")
public class BuscaclienterutBcaCliente implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String rutCliente;
    private String dvCliente;
    private String codEntidad;
    private String codSucursal;
    private String cliente;
    private String valido;
    private String estado;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaclienterutBcaCliente} instance.
     */
    public BuscaclienterutBcaCliente()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code rutCliente}.
     *
     * @return the current value of the property.
     */
    public String getRutCliente()
    {
        return rutCliente;
    }

    /**
     * Changes the value of property {@code rutCliente}.
     *
     * @param value the new value of the property.
     */
    public void setRutCliente(final String value)
    {
        this.rutCliente = value;
    }

    /**
     * Returns the value of property {@code dvCliente}.
     *
     * @return the current value of the property.
     */
    public String getDvCliente()
    {
        return dvCliente;
    }

    /**
     * Changes the value of property {@code dvCliente}.
     *
     * @param value the new value of the property.
     */
    public void setDvCliente(final String value)
    {
        this.dvCliente = value;
    }

    /**
     * Returns the value of property {@code codEntidad}.
     *
     * @return the current value of the property.
     */
    public String getCodEntidad()
    {
        return codEntidad;
    }

    /**
     * Changes the value of property {@code codEntidad}.
     *
     * @param value the new value of the property.
     */
    public void setCodEntidad(final String value)
    {
        this.codEntidad = value;
    }

    /**
     * Returns the value of property {@code codSucursal}.
     *
     * @return the current value of the property.
     */
    public String getCodSucursal()
    {
        return codSucursal;
    }

    /**
     * Changes the value of property {@code codSucursal}.
     *
     * @param value the new value of the property.
     */
    public void setCodSucursal(final String value)
    {
        this.codSucursal = value;
    }

    /**
     * Returns the value of property {@code cliente}.
     *
     * @return the current value of the property.
     */
    public String getCliente()
    {
        return cliente;
    }

    /**
     * Changes the value of property {@code cliente}.
     *
     * @param value the new value of the property.
     */
    public void setCliente(final String value)
    {
        this.cliente = value;
    }

    /**
     * Returns the value of property {@code valido}.
     *
     * @return the current value of the property.
     */
    public String getValido()
    {
        return valido;
    }

    /**
     * Changes the value of property {@code valido}.
     *
     * @param value the new value of the property.
     */
    public void setValido(final String value)
    {
        this.valido = value;
    }

    /**
     * Returns the value of property {@code estado}.
     *
     * @return the current value of the property.
     */
    public String getEstado()
    {
        return estado;
    }

    /**
     * Changes the value of property {@code estado}.
     *
     * @param value the new value of the property.
     */
    public void setEstado(final String value)
    {
        this.estado = value;
    }
}
