/*
 * Source: BuscabanusutieBcaCaller.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * Caller of procedure {@code SolicitudSencillo$BuscaBanUsuTie_bca}.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
public class BuscabanusutieBcaCaller extends ProcedureCaller
{
    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscabanusutieBcaCaller} instance.
     */
    public BuscabanusutieBcaCaller()
    {
    }

    //--------------------------------------------------------------------------
    //-- Execute Methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$BuscaBanUsuTie_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  codEmp {@code Cod_Emp varchar(8)}.
     * @param  cajero {@code Cajero varchar(20)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscabanusutieBcaResult executeProc(final DataSource dataSource, String codEmp, String cajero)
        throws SQLException
    {
        try (final Connection conn = dataSource.getConnection()) {
            return executeProc(conn, codEmp, cajero);
        }
    }

    /**
     * Executes procedure {@code SolicitudSencillo$BuscaBanUsuTie_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  codEmp {@code Cod_Emp varchar(8)}.
     * @param  cajero {@code Cajero varchar(20)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public BuscabanusutieBcaResult executeProc(final Connection conn, String codEmp, String cajero)
        throws SQLException
    {
        final BuscabanusutieBcaResult result = createProcResult();
        final String jdbcURL = getJdbcURL(conn);
        if (jdbcURL.startsWith("jdbc:oracle:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$BuscaBanUsuTie_bca(?,?,?,?)}")) {
                call.setString(1, codEmp);
                call.setString(2, cajero);
                call.registerOutParameter(3, Types.NVARCHAR);
                call.registerOutParameter(4, ORACLE_CURSOR);
                call.execute();
                result.setErrorMessage(call.getString(3));
                result.setBandejas(readBandejas((ResultSet) call.getObject(4)));
            }
        } else if (jdbcURL.startsWith("jdbc:postgresql:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$BuscaBanUsuTie_bca(?,?,?,?)}")) {
                call.setString(1, codEmp);
                call.setString(2, cajero);
                call.registerOutParameter(3, Types.NVARCHAR);
                call.registerOutParameter(4, Types.OTHER);
                call.execute();
                result.setErrorMessage(call.getString(3));
                result.setBandejas(readBandejas((ResultSet) call.getObject(4)));
            }
        } else {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$BuscaBanUsuTie_bca(?,?,?)}")) {
                call.setString(1, codEmp);
                call.setString(2, cajero);
                call.registerOutParameter(3, Types.NVARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset) {
                        updateCount = call.getUpdateCount();
                    } else if (result.getBandejas() == null) {
                        result.setBandejas(readBandejas(call.getResultSet()));
                    } else {
                        unexpectedResultSet(call.getResultSet());
                    }
                    haveRset = call.getMoreResults();
                }
                result.setErrorMessage(call.getString(3));
            }
        }
        return result;
    }

    /**
     * Creates and returns a new instance of {@code BuscabanusutieBcaResult}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscabanusutieBcaResult}.
     *
     * @return a new {@code BuscabanusutieBcaResult} instance.
     */
    protected BuscabanusutieBcaResult createProcResult()
    {
        return new BuscabanusutieBcaResult();
    }

    //--------------------------------------------------------------------------
    //-- BuscabanusutieBcaBandeja ResultSet Methods ----------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts a result set to an array of {@code BuscabanusutieBcaBandeja}.
     *
     * @param  resultSet the result set to convert (can be null).
     * @return an array of {@code BuscabanusutieBcaBandeja} or null.
     * @throws SQLException if an SQL error occurs.
     */
    protected List<BuscabanusutieBcaBandeja> readBandejas(final ResultSet resultSet)
        throws SQLException
    {
        if (resultSet == null)
            return null;
        try {
            // Obtain ordinal (index) numbers of result columns
            final int cIdentificador = resultSet.findColumn("IDENTIFICADOR");
            final int cDescripcion = resultSet.findColumn("DESCRIPCION");
            final int cIdBandejapos = resultSet.findColumn("ID_BANDEJAPOS");
            final int cDesestado = resultSet.findColumn("DESESTADO");
            final int cEstado = resultSet.findColumn("ESTADO");

            // Convert result rows to an array of "BuscabanusutieBcaBandeja"
            final List<BuscabanusutieBcaBandeja> list = new ArrayList<>();
            while (resultSet.next()) {
                final BuscabanusutieBcaBandeja item = createBandeja();
                item.setIdentificador(resultSet.getString(cIdentificador));
                item.setDescripcion(resultSet.getString(cDescripcion));
                item.setIdBandejapos(resultSet.getString(cIdBandejapos));
                item.setDesestado(resultSet.getString(cDesestado));
                item.setEstado(resultSet.getString(cEstado));
                if (filterBandeja(item)) list.add(item);
            }
            return list;
        } finally {
            resultSet.close();
        }
    }

    /**
     * Creates and returns a new instance of {@code BuscabanusutieBcaBandeja}.
     * <p>
     * Can be overridden to return a subtype of {@code BuscabanusutieBcaBandeja}.
     *
     * @return a new {@code BuscabanusutieBcaBandeja} instance.
     */
    protected BuscabanusutieBcaBandeja createBandeja()
    {
        return new BuscabanusutieBcaBandeja();
    }

    /**
     * Returns {@code true} if supplied item should be added to result set.
     * <p>
     * Can be overridden to select which items are added to the result set.
     *
     * @param  item the {@code BuscabanusutieBcaBandeja} to be checked.
     * @return {@code true} if {@code item} should be added to result set.
     * @throws NullPointerException if {@code item} is {@code null}.
     */
    protected boolean filterBandeja(final BuscabanusutieBcaBandeja item)
    {
        return true;
    }

    //--------------------------------------------------------------------------
    //-- Static Methods --------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$BuscaBanUsuTie_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  codEmp {@code Cod_Emp varchar(8)}.
     * @param  cajero {@code Cajero varchar(20)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscabanusutieBcaResult execute(final DataSource dataSource, String codEmp, String cajero)
        throws SQLException
    {
        return new BuscabanusutieBcaCaller().executeProc(dataSource, codEmp, cajero);
    }

    /**
     * Executes procedure {@code SolicitudSencillo$BuscaBanUsuTie_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  codEmp {@code Cod_Emp varchar(8)}.
     * @param  cajero {@code Cajero varchar(20)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static BuscabanusutieBcaResult execute(final Connection conn, String codEmp, String cajero)
        throws SQLException
    {
        return new BuscabanusutieBcaCaller().executeProc(conn, codEmp, cajero);
    }
}
