/*
 * Source: BuscaempresaxestacionBcaSolicitud.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code SOLICITUD} of procedure {@code SolicitudSencillo$BuscaEmpresaXEstacion_bca}.
 *
 * <pre>
 * #ResultSet SOLICITUD SOLICITUDES
 *   #Column  ESTACION             NVARCHAR
 *   #Column  COD_EMP              NVARCHAR
 *   #Column  NOM_EMP              NVARCHAR
 *   #Column  TIPOESTACION         NVARCHAR
 *   #Column  DESCRIPCION          NVARCHAR
 *   #Column  BODEGA               NVARCHAR
 *   #Column  LISTAVENTA           NVARCHAR
 *   #Column  COD_REGION           NVARCHAR
 *   #Column  RAZONSOCIAL_SII      NVARCHAR
 *   #Column  AJUSTESENCILLO       NVARCHAR
 *   #Column  TIPOFAC_ECORETIRO    NVARCHAR
 *   #Column  TIPOFAC_ECODESPACHO  NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "buscaempresaxestacionBcaSolicitud")
@XmlType(name = "BuscaempresaxestacionBcaSolicitud")
public class BuscaempresaxestacionBcaSolicitud implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String estacion;
    private String codEmp;
    private String nomEmp;
    private String tipoestacion;
    private String descripcion;
    private String bodega;
    private String listaventa;
    private String codRegion;
    private String razonsocialSii;
    private String ajustesencillo;
    private String tipofacEcoretiro;
    private String tipofacEcodespacho;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code BuscaempresaxestacionBcaSolicitud} instance.
     */
    public BuscaempresaxestacionBcaSolicitud()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code estacion}.
     *
     * @return the current value of the property.
     */
    public String getEstacion()
    {
        return estacion;
    }

    /**
     * Changes the value of property {@code estacion}.
     *
     * @param value the new value of the property.
     */
    public void setEstacion(final String value)
    {
        this.estacion = value;
    }

    /**
     * Returns the value of property {@code codEmp}.
     *
     * @return the current value of the property.
     */
    public String getCodEmp()
    {
        return codEmp;
    }

    /**
     * Changes the value of property {@code codEmp}.
     *
     * @param value the new value of the property.
     */
    public void setCodEmp(final String value)
    {
        this.codEmp = value;
    }

    /**
     * Returns the value of property {@code nomEmp}.
     *
     * @return the current value of the property.
     */
    public String getNomEmp()
    {
        return nomEmp;
    }

    /**
     * Changes the value of property {@code nomEmp}.
     *
     * @param value the new value of the property.
     */
    public void setNomEmp(final String value)
    {
        this.nomEmp = value;
    }

    /**
     * Returns the value of property {@code tipoestacion}.
     *
     * @return the current value of the property.
     */
    public String getTipoestacion()
    {
        return tipoestacion;
    }

    /**
     * Changes the value of property {@code tipoestacion}.
     *
     * @param value the new value of the property.
     */
    public void setTipoestacion(final String value)
    {
        this.tipoestacion = value;
    }

    /**
     * Returns the value of property {@code descripcion}.
     *
     * @return the current value of the property.
     */
    public String getDescripcion()
    {
        return descripcion;
    }

    /**
     * Changes the value of property {@code descripcion}.
     *
     * @param value the new value of the property.
     */
    public void setDescripcion(final String value)
    {
        this.descripcion = value;
    }

    /**
     * Returns the value of property {@code bodega}.
     *
     * @return the current value of the property.
     */
    public String getBodega()
    {
        return bodega;
    }

    /**
     * Changes the value of property {@code bodega}.
     *
     * @param value the new value of the property.
     */
    public void setBodega(final String value)
    {
        this.bodega = value;
    }

    /**
     * Returns the value of property {@code listaventa}.
     *
     * @return the current value of the property.
     */
    public String getListaventa()
    {
        return listaventa;
    }

    /**
     * Changes the value of property {@code listaventa}.
     *
     * @param value the new value of the property.
     */
    public void setListaventa(final String value)
    {
        this.listaventa = value;
    }

    /**
     * Returns the value of property {@code codRegion}.
     *
     * @return the current value of the property.
     */
    public String getCodRegion()
    {
        return codRegion;
    }

    /**
     * Changes the value of property {@code codRegion}.
     *
     * @param value the new value of the property.
     */
    public void setCodRegion(final String value)
    {
        this.codRegion = value;
    }

    /**
     * Returns the value of property {@code razonsocialSii}.
     *
     * @return the current value of the property.
     */
    public String getRazonsocialSii()
    {
        return razonsocialSii;
    }

    /**
     * Changes the value of property {@code razonsocialSii}.
     *
     * @param value the new value of the property.
     */
    public void setRazonsocialSii(final String value)
    {
        this.razonsocialSii = value;
    }

    /**
     * Returns the value of property {@code ajustesencillo}.
     *
     * @return the current value of the property.
     */
    public String getAjustesencillo()
    {
        return ajustesencillo;
    }

    /**
     * Changes the value of property {@code ajustesencillo}.
     *
     * @param value the new value of the property.
     */
    public void setAjustesencillo(final String value)
    {
        this.ajustesencillo = value;
    }

    /**
     * Returns the value of property {@code tipofacEcoretiro}.
     *
     * @return the current value of the property.
     */
    public String getTipofacEcoretiro()
    {
        return tipofacEcoretiro;
    }

    /**
     * Changes the value of property {@code tipofacEcoretiro}.
     *
     * @param value the new value of the property.
     */
    public void setTipofacEcoretiro(final String value)
    {
        this.tipofacEcoretiro = value;
    }

    /**
     * Returns the value of property {@code tipofacEcodespacho}.
     *
     * @return the current value of the property.
     */
    public String getTipofacEcodespacho()
    {
        return tipofacEcodespacho;
    }

    /**
     * Changes the value of property {@code tipofacEcodespacho}.
     *
     * @param value the new value of the property.
     */
    public void setTipofacEcodespacho(final String value)
    {
        this.tipofacEcodespacho = value;
    }
}
