/*
 * Source: GrabaenviobanInsSolicitud.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code SOLICITUD} of procedure {@code SolicitudSencillo$GrabaEnvioBan_ins}.
 *
 * <pre>
 * #ResultSet SOLICITUD SOLICITUDES
 *   #Column  NRO_INTERNO  NVARCHAR
 *   #Column  FECHAGRAB    NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "grabaenviobanInsSolicitud")
@XmlType(name = "GrabaenviobanInsSolicitud")
public class GrabaenviobanInsSolicitud implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String nroInterno;
    private String fechagrab;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code GrabaenviobanInsSolicitud} instance.
     */
    public GrabaenviobanInsSolicitud()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code nroInterno}.
     *
     * @return the current value of the property.
     */
    public String getNroInterno()
    {
        return nroInterno;
    }

    /**
     * Changes the value of property {@code nroInterno}.
     *
     * @param value the new value of the property.
     */
    public void setNroInterno(final String value)
    {
        this.nroInterno = value;
    }

    /**
     * Returns the value of property {@code fechagrab}.
     *
     * @return the current value of the property.
     */
    public String getFechagrab()
    {
        return fechagrab;
    }

    /**
     * Changes the value of property {@code fechagrab}.
     *
     * @param value the new value of the property.
     */
    public void setFechagrab(final String value)
    {
        this.fechagrab = value;
    }
}
