/*
 * Source: MantusuariosearchBcaCaller.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * Caller of procedure {@code SolicitudSencillo$MantUsuarioSearch_bca}.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
public class MantusuariosearchBcaCaller extends ProcedureCaller
{
    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code MantusuariosearchBcaCaller} instance.
     */
    public MantusuariosearchBcaCaller()
    {
    }

    //--------------------------------------------------------------------------
    //-- Execute Methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$MantUsuarioSearch_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  codVendedor {@code Cod_Vendedor varchar(40)}.
     * @param  codUsuario {@code Cod_Usuario varchar(40)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public MantusuariosearchBcaResult executeProc(final DataSource dataSource, String codVendedor, String codUsuario)
        throws SQLException
    {
        try (final Connection conn = dataSource.getConnection()) {
            return executeProc(conn, codVendedor, codUsuario);
        }
    }

    /**
     * Executes procedure {@code SolicitudSencillo$MantUsuarioSearch_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  codVendedor {@code Cod_Vendedor varchar(40)}.
     * @param  codUsuario {@code Cod_Usuario varchar(40)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public MantusuariosearchBcaResult executeProc(final Connection conn, String codVendedor, String codUsuario)
        throws SQLException
    {
        final MantusuariosearchBcaResult result = createProcResult();
        final String jdbcURL = getJdbcURL(conn);
        if (jdbcURL.startsWith("jdbc:oracle:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$MantUsuarioSearch_bca(?,?,?,?)}")) {
                call.setString(1, codVendedor);
                call.setString(2, codUsuario);
                call.registerOutParameter(3, Types.NVARCHAR);
                call.registerOutParameter(4, ORACLE_CURSOR);
                call.execute();
                result.setErrorMessage(call.getString(3));
                result.setSolicitudes(readSolicitudes((ResultSet) call.getObject(4)));
            }
        } else if (jdbcURL.startsWith("jdbc:postgresql:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$MantUsuarioSearch_bca(?,?,?,?)}")) {
                call.setString(1, codVendedor);
                call.setString(2, codUsuario);
                call.registerOutParameter(3, Types.NVARCHAR);
                call.registerOutParameter(4, Types.OTHER);
                call.execute();
                result.setErrorMessage(call.getString(3));
                result.setSolicitudes(readSolicitudes((ResultSet) call.getObject(4)));
            }
        } else {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$MantUsuarioSearch_bca(?,?,?)}")) {
                call.setString(1, codVendedor);
                call.setString(2, codUsuario);
                call.registerOutParameter(3, Types.NVARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset) {
                        updateCount = call.getUpdateCount();
                    } else if (result.getSolicitudes() == null) {
                        result.setSolicitudes(readSolicitudes(call.getResultSet()));
                    } else {
                        unexpectedResultSet(call.getResultSet());
                    }
                    haveRset = call.getMoreResults();
                }
                result.setErrorMessage(call.getString(3));
            }
        }
        return result;
    }

    /**
     * Creates and returns a new instance of {@code MantusuariosearchBcaResult}.
     * <p>
     * Can be overridden to return a subtype of {@code MantusuariosearchBcaResult}.
     *
     * @return a new {@code MantusuariosearchBcaResult} instance.
     */
    protected MantusuariosearchBcaResult createProcResult()
    {
        return new MantusuariosearchBcaResult();
    }

    //--------------------------------------------------------------------------
    //-- MantusuariosearchBcaSolicitud ResultSet Methods -----------------------
    //--------------------------------------------------------------------------

    /**
     * Converts a result set to an array of {@code MantusuariosearchBcaSolicitud}.
     *
     * @param  resultSet the result set to convert (can be null).
     * @return an array of {@code MantusuariosearchBcaSolicitud} or null.
     * @throws SQLException if an SQL error occurs.
     */
    protected List<MantusuariosearchBcaSolicitud> readSolicitudes(final ResultSet resultSet)
        throws SQLException
    {
        if (resultSet == null)
            return null;
        try {
            // Obtain ordinal (index) numbers of result columns
            final int cCodUsuario = resultSet.findColumn("COD_USUARIO");
            final int cNombres = resultSet.findColumn("NOMBRES");
            final int cApellidoPat = resultSet.findColumn("APELLIDO_PAT");
            final int cApellidoMat = resultSet.findColumn("APELLIDO_MAT");
            final int cUsuEstado = resultSet.findColumn("USU_ESTADO");
            final int cCodVendedor = resultSet.findColumn("COD_VENDEDOR");
            final int cCodAlterno = resultSet.findColumn("COD_ALTERNO");
            final int cCodCargo = resultSet.findColumn("COD_CARGO");
            final int cColor = resultSet.findColumn("COLOR");
            final int cImpportable = resultSet.findColumn("IMPPORTABLE");
            final int cImpnoportable = resultSet.findColumn("IMPNOPORTABLE");
            final int cImpportmade = resultSet.findColumn("IMPPORTMADE");
            final int cImpnopomade = resultSet.findColumn("IMPNOPOMADE");
            final int cTienda = resultSet.findColumn("TIENDA");
            final int cRut = resultSet.findColumn("RUT");
            final int cDescripcioncargo = resultSet.findColumn("DESCRIPCIONCARGO");
            final int cEmail = resultSet.findColumn("EMAIL");
            final int cEmpresa = resultSet.findColumn("EMPRESA");
            final int cBodega = resultSet.findColumn("BODEGA");
            final int cFono1 = resultSet.findColumn("FONO1");
            final int cFono2 = resultSet.findColumn("FONO2");
            final int cIndRetiro = resultSet.findColumn("IND_RETIRO");
            final int cFecharetiro = resultSet.findColumn("FECHARETIRO");
            final int cFechacumpleano = resultSet.findColumn("FECHACUMPLEANO");
            final int cIdCargo = resultSet.findColumn("ID_CARGO");
            final int cUsuario = resultSet.findColumn("USUARIO");

            // Convert result rows to an array of "MantusuariosearchBcaSolicitud"
            final List<MantusuariosearchBcaSolicitud> list = new ArrayList<>();
            while (resultSet.next()) {
                final MantusuariosearchBcaSolicitud item = createSolicitud();
                item.setCodUsuario(resultSet.getString(cCodUsuario));
                item.setNombres(resultSet.getString(cNombres));
                item.setApellidoPat(resultSet.getString(cApellidoPat));
                item.setApellidoMat(resultSet.getString(cApellidoMat));
                item.setUsuEstado(resultSet.getString(cUsuEstado));
                item.setCodVendedor(resultSet.getString(cCodVendedor));
                item.setCodAlterno(resultSet.getString(cCodAlterno));
                item.setCodCargo(resultSet.getString(cCodCargo));
                item.setColor(resultSet.getString(cColor));
                item.setImpportable(resultSet.getString(cImpportable));
                item.setImpnoportable(resultSet.getString(cImpnoportable));
                item.setImpportmade(resultSet.getString(cImpportmade));
                item.setImpnopomade(resultSet.getString(cImpnopomade));
                item.setTienda(resultSet.getString(cTienda));
                item.setRut(resultSet.getString(cRut));
                item.setDescripcioncargo(resultSet.getString(cDescripcioncargo));
                item.setEmail(resultSet.getString(cEmail));
                item.setEmpresa(resultSet.getString(cEmpresa));
                item.setBodega(resultSet.getString(cBodega));
                item.setFono1(resultSet.getString(cFono1));
                item.setFono2(resultSet.getString(cFono2));
                item.setIndRetiro(resultSet.getString(cIndRetiro));
                item.setFecharetiro(resultSet.getString(cFecharetiro));
                item.setFechacumpleano(resultSet.getString(cFechacumpleano));
                item.setIdCargo(resultSet.getString(cIdCargo));
                item.setUsuario(resultSet.getString(cUsuario));
                if (filterSolicitud(item)) list.add(item);
            }
            return list;
        } finally {
            resultSet.close();
        }
    }

    /**
     * Creates and returns a new instance of {@code MantusuariosearchBcaSolicitud}.
     * <p>
     * Can be overridden to return a subtype of {@code MantusuariosearchBcaSolicitud}.
     *
     * @return a new {@code MantusuariosearchBcaSolicitud} instance.
     */
    protected MantusuariosearchBcaSolicitud createSolicitud()
    {
        return new MantusuariosearchBcaSolicitud();
    }

    /**
     * Returns {@code true} if supplied item should be added to result set.
     * <p>
     * Can be overridden to select which items are added to the result set.
     *
     * @param  item the {@code MantusuariosearchBcaSolicitud} to be checked.
     * @return {@code true} if {@code item} should be added to result set.
     * @throws NullPointerException if {@code item} is {@code null}.
     */
    protected boolean filterSolicitud(final MantusuariosearchBcaSolicitud item)
    {
        return true;
    }

    //--------------------------------------------------------------------------
    //-- Static Methods --------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$MantUsuarioSearch_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  codVendedor {@code Cod_Vendedor varchar(40)}.
     * @param  codUsuario {@code Cod_Usuario varchar(40)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static MantusuariosearchBcaResult execute(final DataSource dataSource, String codVendedor, String codUsuario)
        throws SQLException
    {
        return new MantusuariosearchBcaCaller().executeProc(dataSource, codVendedor, codUsuario);
    }

    /**
     * Executes procedure {@code SolicitudSencillo$MantUsuarioSearch_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  codVendedor {@code Cod_Vendedor varchar(40)}.
     * @param  codUsuario {@code Cod_Usuario varchar(40)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static MantusuariosearchBcaResult execute(final Connection conn, String codVendedor, String codUsuario)
        throws SQLException
    {
        return new MantusuariosearchBcaCaller().executeProc(conn, codVendedor, codUsuario);
    }
}
