/*
 * Source: MantusuariosearchBcaSolicitud.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code SOLICITUD} of procedure {@code SolicitudSencillo$MantUsuarioSearch_bca}.
 *
 * <pre>
 * #ResultSet SOLICITUD SOLICITUDES
 *   #Column  COD_USUARIO       NVARCHAR
 *   #Column  NOMBRES           NVARCHAR
 *   #Column  APELLIDO_PAT      NVARCHAR
 *   #Column  APELLIDO_MAT      NVARCHAR
 *   #Column  USU_ESTADO        NVARCHAR
 *   #Column  COD_VENDEDOR      NVARCHAR
 *   #Column  COD_ALTERNO       NVARCHAR
 *   #Column  COD_CARGO         NVARCHAR
 *   #Column  COLOR             NVARCHAR
 *   #Column  IMPPORTABLE       NVARCHAR
 *   #Column  IMPNOPORTABLE     NVARCHAR
 *   #Column  IMPPORTMADE       NVARCHAR
 *   #Column  IMPNOPOMADE       NVARCHAR
 *   #Column  TIENDA            NVARCHAR
 *   #Column  RUT               NVARCHAR
 *   #Column  DESCRIPCIONCARGO  NVARCHAR
 *   #Column  EMAIL             NVARCHAR
 *   #Column  EMPRESA           NVARCHAR
 *   #Column  BODEGA            NVARCHAR
 *   #Column  FONO1             NVARCHAR
 *   #Column  FONO2             NVARCHAR
 *   #Column  IND_RETIRO        NVARCHAR
 *   #Column  FECHARETIRO       NVARCHAR
 *   #Column  FECHACUMPLEANO    NVARCHAR
 *   #Column  ID_CARGO          NVARCHAR
 *   #Column  USUARIO           NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "mantusuariosearchBcaSolicitud")
@XmlType(name = "MantusuariosearchBcaSolicitud")
public class MantusuariosearchBcaSolicitud implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String codUsuario;
    private String nombres;
    private String apellidoPat;
    private String apellidoMat;
    private String usuEstado;
    private String codVendedor;
    private String codAlterno;
    private String codCargo;
    private String color;
    private String impportable;
    private String impnoportable;
    private String impportmade;
    private String impnopomade;
    private String tienda;
    private String rut;
    private String descripcioncargo;
    private String email;
    private String empresa;
    private String bodega;
    private String fono1;
    private String fono2;
    private String indRetiro;
    private String fecharetiro;
    private String fechacumpleano;
    private String idCargo;
    private String usuario;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code MantusuariosearchBcaSolicitud} instance.
     */
    public MantusuariosearchBcaSolicitud()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code codUsuario}.
     *
     * @return the current value of the property.
     */
    public String getCodUsuario()
    {
        return codUsuario;
    }

    /**
     * Changes the value of property {@code codUsuario}.
     *
     * @param value the new value of the property.
     */
    public void setCodUsuario(final String value)
    {
        this.codUsuario = value;
    }

    /**
     * Returns the value of property {@code nombres}.
     *
     * @return the current value of the property.
     */
    public String getNombres()
    {
        return nombres;
    }

    /**
     * Changes the value of property {@code nombres}.
     *
     * @param value the new value of the property.
     */
    public void setNombres(final String value)
    {
        this.nombres = value;
    }

    /**
     * Returns the value of property {@code apellidoPat}.
     *
     * @return the current value of the property.
     */
    public String getApellidoPat()
    {
        return apellidoPat;
    }

    /**
     * Changes the value of property {@code apellidoPat}.
     *
     * @param value the new value of the property.
     */
    public void setApellidoPat(final String value)
    {
        this.apellidoPat = value;
    }

    /**
     * Returns the value of property {@code apellidoMat}.
     *
     * @return the current value of the property.
     */
    public String getApellidoMat()
    {
        return apellidoMat;
    }

    /**
     * Changes the value of property {@code apellidoMat}.
     *
     * @param value the new value of the property.
     */
    public void setApellidoMat(final String value)
    {
        this.apellidoMat = value;
    }

    /**
     * Returns the value of property {@code usuEstado}.
     *
     * @return the current value of the property.
     */
    public String getUsuEstado()
    {
        return usuEstado;
    }

    /**
     * Changes the value of property {@code usuEstado}.
     *
     * @param value the new value of the property.
     */
    public void setUsuEstado(final String value)
    {
        this.usuEstado = value;
    }

    /**
     * Returns the value of property {@code codVendedor}.
     *
     * @return the current value of the property.
     */
    public String getCodVendedor()
    {
        return codVendedor;
    }

    /**
     * Changes the value of property {@code codVendedor}.
     *
     * @param value the new value of the property.
     */
    public void setCodVendedor(final String value)
    {
        this.codVendedor = value;
    }

    /**
     * Returns the value of property {@code codAlterno}.
     *
     * @return the current value of the property.
     */
    public String getCodAlterno()
    {
        return codAlterno;
    }

    /**
     * Changes the value of property {@code codAlterno}.
     *
     * @param value the new value of the property.
     */
    public void setCodAlterno(final String value)
    {
        this.codAlterno = value;
    }

    /**
     * Returns the value of property {@code codCargo}.
     *
     * @return the current value of the property.
     */
    public String getCodCargo()
    {
        return codCargo;
    }

    /**
     * Changes the value of property {@code codCargo}.
     *
     * @param value the new value of the property.
     */
    public void setCodCargo(final String value)
    {
        this.codCargo = value;
    }

    /**
     * Returns the value of property {@code color}.
     *
     * @return the current value of the property.
     */
    public String getColor()
    {
        return color;
    }

    /**
     * Changes the value of property {@code color}.
     *
     * @param value the new value of the property.
     */
    public void setColor(final String value)
    {
        this.color = value;
    }

    /**
     * Returns the value of property {@code impportable}.
     *
     * @return the current value of the property.
     */
    public String getImpportable()
    {
        return impportable;
    }

    /**
     * Changes the value of property {@code impportable}.
     *
     * @param value the new value of the property.
     */
    public void setImpportable(final String value)
    {
        this.impportable = value;
    }

    /**
     * Returns the value of property {@code impnoportable}.
     *
     * @return the current value of the property.
     */
    public String getImpnoportable()
    {
        return impnoportable;
    }

    /**
     * Changes the value of property {@code impnoportable}.
     *
     * @param value the new value of the property.
     */
    public void setImpnoportable(final String value)
    {
        this.impnoportable = value;
    }

    /**
     * Returns the value of property {@code impportmade}.
     *
     * @return the current value of the property.
     */
    public String getImpportmade()
    {
        return impportmade;
    }

    /**
     * Changes the value of property {@code impportmade}.
     *
     * @param value the new value of the property.
     */
    public void setImpportmade(final String value)
    {
        this.impportmade = value;
    }

    /**
     * Returns the value of property {@code impnopomade}.
     *
     * @return the current value of the property.
     */
    public String getImpnopomade()
    {
        return impnopomade;
    }

    /**
     * Changes the value of property {@code impnopomade}.
     *
     * @param value the new value of the property.
     */
    public void setImpnopomade(final String value)
    {
        this.impnopomade = value;
    }

    /**
     * Returns the value of property {@code tienda}.
     *
     * @return the current value of the property.
     */
    public String getTienda()
    {
        return tienda;
    }

    /**
     * Changes the value of property {@code tienda}.
     *
     * @param value the new value of the property.
     */
    public void setTienda(final String value)
    {
        this.tienda = value;
    }

    /**
     * Returns the value of property {@code rut}.
     *
     * @return the current value of the property.
     */
    public String getRut()
    {
        return rut;
    }

    /**
     * Changes the value of property {@code rut}.
     *
     * @param value the new value of the property.
     */
    public void setRut(final String value)
    {
        this.rut = value;
    }

    /**
     * Returns the value of property {@code descripcioncargo}.
     *
     * @return the current value of the property.
     */
    public String getDescripcioncargo()
    {
        return descripcioncargo;
    }

    /**
     * Changes the value of property {@code descripcioncargo}.
     *
     * @param value the new value of the property.
     */
    public void setDescripcioncargo(final String value)
    {
        this.descripcioncargo = value;
    }

    /**
     * Returns the value of property {@code email}.
     *
     * @return the current value of the property.
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * Changes the value of property {@code email}.
     *
     * @param value the new value of the property.
     */
    public void setEmail(final String value)
    {
        this.email = value;
    }

    /**
     * Returns the value of property {@code empresa}.
     *
     * @return the current value of the property.
     */
    public String getEmpresa()
    {
        return empresa;
    }

    /**
     * Changes the value of property {@code empresa}.
     *
     * @param value the new value of the property.
     */
    public void setEmpresa(final String value)
    {
        this.empresa = value;
    }

    /**
     * Returns the value of property {@code bodega}.
     *
     * @return the current value of the property.
     */
    public String getBodega()
    {
        return bodega;
    }

    /**
     * Changes the value of property {@code bodega}.
     *
     * @param value the new value of the property.
     */
    public void setBodega(final String value)
    {
        this.bodega = value;
    }

    /**
     * Returns the value of property {@code fono1}.
     *
     * @return the current value of the property.
     */
    public String getFono1()
    {
        return fono1;
    }

    /**
     * Changes the value of property {@code fono1}.
     *
     * @param value the new value of the property.
     */
    public void setFono1(final String value)
    {
        this.fono1 = value;
    }

    /**
     * Returns the value of property {@code fono2}.
     *
     * @return the current value of the property.
     */
    public String getFono2()
    {
        return fono2;
    }

    /**
     * Changes the value of property {@code fono2}.
     *
     * @param value the new value of the property.
     */
    public void setFono2(final String value)
    {
        this.fono2 = value;
    }

    /**
     * Returns the value of property {@code indRetiro}.
     *
     * @return the current value of the property.
     */
    public String getIndRetiro()
    {
        return indRetiro;
    }

    /**
     * Changes the value of property {@code indRetiro}.
     *
     * @param value the new value of the property.
     */
    public void setIndRetiro(final String value)
    {
        this.indRetiro = value;
    }

    /**
     * Returns the value of property {@code fecharetiro}.
     *
     * @return the current value of the property.
     */
    public String getFecharetiro()
    {
        return fecharetiro;
    }

    /**
     * Changes the value of property {@code fecharetiro}.
     *
     * @param value the new value of the property.
     */
    public void setFecharetiro(final String value)
    {
        this.fecharetiro = value;
    }

    /**
     * Returns the value of property {@code fechacumpleano}.
     *
     * @return the current value of the property.
     */
    public String getFechacumpleano()
    {
        return fechacumpleano;
    }

    /**
     * Changes the value of property {@code fechacumpleano}.
     *
     * @param value the new value of the property.
     */
    public void setFechacumpleano(final String value)
    {
        this.fechacumpleano = value;
    }

    /**
     * Returns the value of property {@code idCargo}.
     *
     * @return the current value of the property.
     */
    public String getIdCargo()
    {
        return idCargo;
    }

    /**
     * Changes the value of property {@code idCargo}.
     *
     * @param value the new value of the property.
     */
    public void setIdCargo(final String value)
    {
        this.idCargo = value;
    }

    /**
     * Returns the value of property {@code usuario}.
     *
     * @return the current value of the property.
     */
    public String getUsuario()
    {
        return usuario;
    }

    /**
     * Changes the value of property {@code usuario}.
     *
     * @param value the new value of the property.
     */
    public void setUsuario(final String value)
    {
        this.usuario = value;
    }
}
