/*
 * Source: TraedenmonBcaCaller.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

/**
 * Caller of procedure {@code SolicitudSencillo$TraeDenMon_bca}.
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
public class TraedenmonBcaCaller extends ProcedureCaller
{
    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code TraedenmonBcaCaller} instance.
     */
    public TraedenmonBcaCaller()
    {
    }

    //--------------------------------------------------------------------------
    //-- Execute Methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$TraeDenMon_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  estado {@code Estado varchar(1)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public TraedenmonBcaResult executeProc(final DataSource dataSource, String estado)
        throws SQLException
    {
        try (final Connection conn = dataSource.getConnection()) {
            return executeProc(conn, estado);
        }
    }

    /**
     * Executes procedure {@code SolicitudSencillo$TraeDenMon_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  estado {@code Estado varchar(1)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public TraedenmonBcaResult executeProc(final Connection conn, String estado)
        throws SQLException
    {
        final TraedenmonBcaResult result = createProcResult();
        final String jdbcURL = getJdbcURL(conn);
        if (jdbcURL.startsWith("jdbc:oracle:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$TraeDenMon_bca(?,?,?)}")) {
                call.setString(1, estado);
                call.registerOutParameter(2, Types.NVARCHAR);
                call.registerOutParameter(3, ORACLE_CURSOR);
                call.execute();
                result.setErrorMessage(call.getString(2));
                result.setSolicitudes(readSolicitudes((ResultSet) call.getObject(3)));
            }
        } else if (jdbcURL.startsWith("jdbc:postgresql:")) {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$TraeDenMon_bca(?,?,?)}")) {
                call.setString(1, estado);
                call.registerOutParameter(2, Types.NVARCHAR);
                call.registerOutParameter(3, Types.OTHER);
                call.execute();
                result.setErrorMessage(call.getString(2));
                result.setSolicitudes(readSolicitudes((ResultSet) call.getObject(3)));
            }
        } else {
            try (final CallableStatement call = prepareCall(conn, "{call SolicitudSencillo$TraeDenMon_bca(?,?)}")) {
                call.setString(1, estado);
                call.registerOutParameter(2, Types.NVARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset) {
                        updateCount = call.getUpdateCount();
                    } else if (result.getSolicitudes() == null) {
                        result.setSolicitudes(readSolicitudes(call.getResultSet()));
                    } else {
                        unexpectedResultSet(call.getResultSet());
                    }
                    haveRset = call.getMoreResults();
                }
                result.setErrorMessage(call.getString(2));
            }
        }
        return result;
    }

    /**
     * Creates and returns a new instance of {@code TraedenmonBcaResult}.
     * <p>
     * Can be overridden to return a subtype of {@code TraedenmonBcaResult}.
     *
     * @return a new {@code TraedenmonBcaResult} instance.
     */
    protected TraedenmonBcaResult createProcResult()
    {
        return new TraedenmonBcaResult();
    }

    //--------------------------------------------------------------------------
    //-- TraedenmonBcaSolicitud ResultSet Methods ------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts a result set to an array of {@code TraedenmonBcaSolicitud}.
     *
     * @param  resultSet the result set to convert (can be null).
     * @return an array of {@code TraedenmonBcaSolicitud} or null.
     * @throws SQLException if an SQL error occurs.
     */
    protected List<TraedenmonBcaSolicitud> readSolicitudes(final ResultSet resultSet)
        throws SQLException
    {
        if (resultSet == null)
            return null;
        try {
            // Obtain ordinal (index) numbers of result columns
            final int cCodigo = resultSet.findColumn("CODIGO");
            final int cGlosa = resultSet.findColumn("GLOSA");
            final int cValor = resultSet.findColumn("VALOR");
            final int cEstado = resultSet.findColumn("ESTADO");

            // Convert result rows to an array of "TraedenmonBcaSolicitud"
            final List<TraedenmonBcaSolicitud> list = new ArrayList<>();
            while (resultSet.next()) {
                final TraedenmonBcaSolicitud item = createSolicitud();
                item.setCodigo(resultSet.getString(cCodigo));
                item.setGlosa(resultSet.getString(cGlosa));
                item.setValor(resultSet.getString(cValor));
                item.setEstado(resultSet.getString(cEstado));
                if (filterSolicitud(item)) list.add(item);
            }
            return list;
        } finally {
            resultSet.close();
        }
    }

    /**
     * Creates and returns a new instance of {@code TraedenmonBcaSolicitud}.
     * <p>
     * Can be overridden to return a subtype of {@code TraedenmonBcaSolicitud}.
     *
     * @return a new {@code TraedenmonBcaSolicitud} instance.
     */
    protected TraedenmonBcaSolicitud createSolicitud()
    {
        return new TraedenmonBcaSolicitud();
    }

    /**
     * Returns {@code true} if supplied item should be added to result set.
     * <p>
     * Can be overridden to select which items are added to the result set.
     *
     * @param  item the {@code TraedenmonBcaSolicitud} to be checked.
     * @return {@code true} if {@code item} should be added to result set.
     * @throws NullPointerException if {@code item} is {@code null}.
     */
    protected boolean filterSolicitud(final TraedenmonBcaSolicitud item)
    {
        return true;
    }

    //--------------------------------------------------------------------------
    //-- Static Methods --------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Executes procedure {@code SolicitudSencillo$TraeDenMon_bca} using a data source.
     *
     * @param  dataSource the connection data source.
     * @param  estado {@code Estado varchar(1)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static TraedenmonBcaResult execute(final DataSource dataSource, String estado)
        throws SQLException
    {
        return new TraedenmonBcaCaller().executeProc(dataSource, estado);
    }

    /**
     * Executes procedure {@code SolicitudSencillo$TraeDenMon_bca} using a connection.
     *
     * @param  conn the database connection.
     * @param  estado {@code Estado varchar(1)}.
     * @return the output parameters and result sets of the procedure.
     * @throws SQLException if an SQL error occurs.
     */
    public static TraedenmonBcaResult execute(final Connection conn, String estado)
        throws SQLException
    {
        return new TraedenmonBcaCaller().executeProc(conn, estado);
    }
}
