/*
 * Source: TraedenmonBcaSolicitud.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Row of result set {@code SOLICITUD} of procedure {@code SolicitudSencillo$TraeDenMon_bca}.
 *
 * <pre>
 * #ResultSet SOLICITUD SOLICITUDES
 *   #Column  CODIGO  NVARCHAR
 *   #Column  GLOSA   NVARCHAR
 *   #Column  VALOR   NVARCHAR
 *   #Column  ESTADO  NVARCHAR
 * #EndResultSet
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "traedenmonBcaSolicitud")
@XmlType(name = "TraedenmonBcaSolicitud")
public class TraedenmonBcaSolicitud implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String codigo;
    private String glosa;
    private String valor;
    private String estado;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code TraedenmonBcaSolicitud} instance.
     */
    public TraedenmonBcaSolicitud()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code codigo}.
     *
     * @return the current value of the property.
     */
    public String getCodigo()
    {
        return codigo;
    }

    /**
     * Changes the value of property {@code codigo}.
     *
     * @param value the new value of the property.
     */
    public void setCodigo(final String value)
    {
        this.codigo = value;
    }

    /**
     * Returns the value of property {@code glosa}.
     *
     * @return the current value of the property.
     */
    public String getGlosa()
    {
        return glosa;
    }

    /**
     * Changes the value of property {@code glosa}.
     *
     * @param value the new value of the property.
     */
    public void setGlosa(final String value)
    {
        this.glosa = value;
    }

    /**
     * Returns the value of property {@code valor}.
     *
     * @return the current value of the property.
     */
    public String getValor()
    {
        return valor;
    }

    /**
     * Changes the value of property {@code valor}.
     *
     * @param value the new value of the property.
     */
    public void setValor(final String value)
    {
        this.valor = value;
    }

    /**
     * Returns the value of property {@code estado}.
     *
     * @return the current value of the property.
     */
    public String getEstado()
    {
        return estado;
    }

    /**
     * Changes the value of property {@code estado}.
     *
     * @param value the new value of the property.
     */
    public void setEstado(final String value)
    {
        this.estado = value;
    }
}
