/*
 * Source: TraesolicitudcjBcaResult.java - Generated by OBCOM SQL Wizard 1.158
 * Author: Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 *
 * Copyright (c) IMPERIAL S.A. All rights reserved.
 * 
 * All  rights  to  this product are owned by IMPERIAL S.A. and may only be used
 * under the terms of its associated license document. You may NOT copy, modify,
 * sublicense,  or  distribute  this  source  file  or  portions  of  it  unless
 * previously authorized in writing by IMPERIAL S.A. In any event,  this  notice
 * and above copyright must always be included verbatim with this file.
 */

package cl.imperial.sencillosolicitud.ws;

import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Results of procedure {@code SolicitudSencillo$TraeSolicitudCJ_bca}.
 *
 * <pre>
 * Error_Message  nvarchar   Output
 * VOUCHER        ResultSet  Output
 * EFECTIVO       ResultSet  Output
 * DOCUMENTO      ResultSet  Output
 * SALDO          ResultSet  Output
 * </pre>
 *
 * @author Cesar Luis Gonzalez-Rubio Chacin (Imperial S.A.)
 */
@XmlRootElement(name = "traesolicitudcjBcaResult")
@XmlType(name = "TraesolicitudcjBcaResult")
public class TraesolicitudcjBcaResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private String errorMessage;
    private List<TraesolicitudcjBcaVoucher> vouchers;
    private List<TraesolicitudcjBcaEfectivo> efectivos;
    private List<TraesolicitudcjBcaDocumento> documentos;
    private List<TraesolicitudcjBcaSaldo> saldos;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code TraesolicitudcjBcaResult} instance.
     */
    public TraesolicitudcjBcaResult()
    {
    }

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the value of property {@code errorMessage}.
     *
     * @return the current value of the property.
     */
    public String getErrorMessage()
    {
        return errorMessage;
    }

    /**
     * Changes the value of property {@code errorMessage}.
     *
     * @param value the new value of the property.
     */
    public void setErrorMessage(final String value)
    {
        this.errorMessage = value;
    }

    /**
     * Returns the value of property {@code vouchers}.
     *
     * @return the current value of the property.
     */
    public List<TraesolicitudcjBcaVoucher> getVouchers()
    {
        return vouchers;
    }

    /**
     * Changes the value of property {@code vouchers}.
     *
     * @param value the new value of the property.
     */
    public void setVouchers(final List<TraesolicitudcjBcaVoucher> value)
    {
        this.vouchers = value;
    }

    /**
     * Returns the value of property {@code efectivos}.
     *
     * @return the current value of the property.
     */
    public List<TraesolicitudcjBcaEfectivo> getEfectivos()
    {
        return efectivos;
    }

    /**
     * Changes the value of property {@code efectivos}.
     *
     * @param value the new value of the property.
     */
    public void setEfectivos(final List<TraesolicitudcjBcaEfectivo> value)
    {
        this.efectivos = value;
    }

    /**
     * Returns the value of property {@code documentos}.
     *
     * @return the current value of the property.
     */
    public List<TraesolicitudcjBcaDocumento> getDocumentos()
    {
        return documentos;
    }

    /**
     * Changes the value of property {@code documentos}.
     *
     * @param value the new value of the property.
     */
    public void setDocumentos(final List<TraesolicitudcjBcaDocumento> value)
    {
        this.documentos = value;
    }

    /**
     * Returns the value of property {@code saldos}.
     *
     * @return the current value of the property.
     */
    public List<TraesolicitudcjBcaSaldo> getSaldos()
    {
        return saldos;
    }

    /**
     * Changes the value of property {@code saldos}.
     *
     * @param value the new value of the property.
     */
    public void setSaldos(final List<TraesolicitudcjBcaSaldo> value)
    {
        this.saldos = value;
    }
}
