
package cl.imperial.cajaunificada.ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CajaUnificadaWeb", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CajaUnificadaWeb {


    /**
     * 
     * @param profileCode
     * @param stationName
     * @param userCode
     * @return
     *     returns cl.imperial.cajaunificada.ws.StartupResult
     * @throws CajaUnificadaWebException
     */
    @WebMethod
    @WebResult(name = "startupResult", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
    @RequestWrapper(localName = "startup", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.Startup")
    @ResponseWrapper(localName = "startupResponse", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.StartupResponse")
    @Action(input = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/startupRequest", output = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/startupResponse", fault = {
        @FaultAction(className = CajaUnificadaWebException.class, value = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/startup/Fault/CajaUnificadaWebException")
    })
    public StartupResult startup(
        @WebParam(name = "userCode", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        String userCode,
        @WebParam(name = "profileCode", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        BigDecimal profileCode,
        @WebParam(name = "stationName", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        String stationName)
        throws CajaUnificadaWebException
    ;

    /**
     * 
     * @param profileCode
     * @param stationName
     * @param nroInterno
     * @param codEmp
     * @param userCode
     * @return
     *     returns cl.imperial.cajaunificada.ws.ValeGetResult
     * @throws CajaUnificadaWebException
     */
    @WebMethod
    @WebResult(name = "valeGetResult", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
    @RequestWrapper(localName = "valeGet", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.ValeGet")
    @ResponseWrapper(localName = "valeGetResponse", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.ValeGetResponse")
    @Action(input = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/valeGetRequest", output = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/valeGetResponse", fault = {
        @FaultAction(className = CajaUnificadaWebException.class, value = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/valeGet/Fault/CajaUnificadaWebException")
    })
    public ValeGetResult valeGet(
        @WebParam(name = "userCode", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        String userCode,
        @WebParam(name = "profileCode", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        BigDecimal profileCode,
        @WebParam(name = "stationName", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        String stationName,
        @WebParam(name = "nroInterno", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        int nroInterno,
        @WebParam(name = "codEmp", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        String codEmp)
        throws CajaUnificadaWebException
    ;

    /**
     * 
     * @param nroInterno
     * @return
     *     returns cl.imperial.cajaunificada.ws.RegistraPagoResult
     * @throws CajaUnificadaWebException
     */
    @WebMethod
    @WebResult(name = "registraPagoResult", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
    @RequestWrapper(localName = "registraPago", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.RegistraPago")
    @ResponseWrapper(localName = "registraPagoResponse", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada", className = "cl.imperial.cajaunificada.ws.RegistraPagoResponse")
    @Action(input = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/registraPagoRequest", output = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/registraPagoResponse", fault = {
        @FaultAction(className = CajaUnificadaWebException.class, value = "http://ws.cajaunificada.imperial.cl/cajaunificada/CajaUnificadaWeb/registraPago/Fault/CajaUnificadaWebException")
    })
    public RegistraPagoResult registraPago(
        @WebParam(name = "nroInterno", targetNamespace = "http://ws.cajaunificada.imperial.cl/cajaunificada")
        int nroInterno)
        throws CajaUnificadaWebException
    ;

}
